### ISSUE TITLE
Flask won't start in the Python 3.4 debugger

### ISSUE THREAD

**Issue by tomkcook** [pallets/flask#1437]
Test code:

```
import flask
app = flask.Flask()
app.run
```

Run like this:

```
$ pdb3 test.py
> /home/tkcook/scratch/python/test.py(1)<module>()
-> import flask
(Pdb) cont
Traceback (most recent call last):
  File "/usr/lib/python3.4/importlib/util.py", line 95, in find_spec
    spec = module.__spec__
AttributeError: 'module' object has no attribute '__spec__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/pkgutil.py", line 481, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/usr/lib/python3.4/importlib/util.py", line 97, in find_spec
    raise ValueError('{}.__spec__ is not set'.format(name))
ValueError: __main__.__spec__ is not set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/pdb.py", line 1661, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.4/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/usr/lib/python3.4/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/tkcook/scratch/python/test.py", line 1, in <module>
    import flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 331, in __init__
    instance_path = self.auto_find_instance_path()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 622, in auto_find_instance_path
    prefix, package_path = find_package(self.import_name)
  File "/usr/lib/python3/dist-packages/flask/helpers.py", line 661, in find_package
    loader = pkgutil.get_loader(root_mod_name)
  File "/usr/lib/python3.4/pkgutil.py", line 467, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python3.4/pkgutil.py", line 487, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for '__main__' (<class 'ValueError'>: __main__.__spec__ is not set)
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python3.4/pkgutil.py(487)find_loader()
-> raise ImportError(msg.format(fullname, type(ex), ex)) from ex
```

Is there a workaround for this?

**Comment by methane** [comment]
Does it work on normal Python 3? (without PDB?)
Does it relate to #1101?

**Comment by tomkcook** [comment]
It works on python3.4 without pdb.  I'm not sure if it relates to #1011, though I'd guess so (it seems to be a very similar error in the same location).

**Comment by tomkcook** [comment]
Yes, it is related to #1011 but not the same.  On python3.4, the AttributeError doesn't get as far as helper.py:664 and it's necessary to catch ImportError instead.  ie:

        root_mod_name = import_name.split('.')[0]
        try:
            loader = pkgutil.get_loader(root_mod_name)
        except AttributeError:
            loader = None
        except ImportError:
            loader = None

**Comment by brianrusso** [comment]
Works fine on python 3.5.2
