### ISSUE TITLE
Reload is not active for all my running Flask instances in debug mode

### ISSUE THREAD

**Issue by k3z** [pallets/flask#1705]
I need to run several flask apps at the same time in my dev environment. 
All apps run in a Vagrant box on Debian 8 with Flaks 0.10.1

When I start in a shell the first flask app with debug and reload enabled and I touch a file on the project, all works fine. The flask app reload and I see the changes.
When I start another flask app in a second shell in debug mode at the same time, the app won’t reload.

In all cases, only the first app reload.

When I quit the app that won’t reload, I get this error.

    Exception in thread Thread-2 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
      File "/home/politis/frontend.dev/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 200, in run
    <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
    Exception in thread Thread-1 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
      File "/usr/lib/python2.7/threading.py", line 763, in run
      File "/home/politis/frontend.dev/local/lib/python2.7/site-packages/werkzeug/serving.py", line 657, in inner
      File "/home/politis/frontend.dev/local/lib/python2.7/site-packages/werkzeug/serving.py", line 497, in serve_forever
      File "/usr/lib/python2.7/SocketServer.py", line 241, in serve_forever
      File "/usr/lib/python2.7/threading.py", line 586, in set
      File "/usr/lib/python2.7/threading.py", line 407, in notifyAll

**Comment by davidism** [comment]
I can't reproduce this error.  I start two separate apps, or two of the same app, on different ports, and both reloaders work.  Need more information to continue.  Is there a minimal app that exhibits this when run multiple times?

**Comment by k3z** [comment]
Thank you. I will try with two minimal projects to see if I can reproduce my bug in the environment and comme back with more information.
