### ISSUE TITLE
Travis 3.3-devel job fails with error about urllib2 in Werkzeug

### ISSUE THREAD

**Issue by davidism** [pallets/flask#1893]
https://travis-ci.org/pallets/flask/jobs/135626173

~~~python-traceback
Traceback (most recent call last):
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/werkzeug/http.py", line 26, in <module>
    from urllib2 import parse_http_list as _parse_list_header, \
ImportError: No module named 'urllib2'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/home/travis/build/pallets/flask/tests/conftest.py", line 9, in <module>
    import flask
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/home/travis/build/pallets/flask/.tox/py-devel/lib/python3.3/site-packages/werkzeug/http.py", line 29, in <module>
    from urllib.request import parse_http_list as _parse_list_header, \
ImportError: cannot import name unquote_to_bytes
~~~

I can't reproduce this locally.  Re-running the job still fails.

**Comment by untitaker** [comment]
https://github.com/pallets/werkzeug/pull/946

**Comment by davidism** [comment]
Should be `from urllib.parse import unquote_to_bytes`, just happens to get imported in `.request` in 3.4+.

**Comment by untitaker** [comment]
Merged and restarted all failing builds.
