### ISSUE TITLE
test_client post cannot handle JSON list

### ISSUE THREAD

**Issue by maximecharron** [pallets/flask#1899]
I have the following object: 

```
 dict(username="test",
       repository="http://github.com",
       foo=[dict(name="test", version="1.1.3")])
```
it gives the following json when dumping it: 
```
{"username": "test", "repository": "http://github.com", "foo": [{"name": "test", "version": "1.1.3"}]}
```

When sending it in a post like that:
```
self.app = mainweb.webapp.test_client()
response = self.app.post('/foo/', data=request) # where request is the object mentionned before
```

it gives the following error:

```
Traceback (most recent call last):
  File "C:\cygwin64\home\xyz\devel\foo\test\foo\functional\test_functionnal.py", line 20, in test_given_valid_request_when_post_then_valid_response
    response = self.app.post('/foo/', data=request)
  File "C:\Python3.5.1\lib\site-packages\werkzeug\test.py", line 788, in post
    return self.open(*args, **kw)
  File "C:\Python3.5.1\lib\site-packages\flask\testing.py", line 103, in open
    builder = make_test_environ_builder(self.application, *args, **kwargs)
  File "C:\Python3.5.1\lib\site-packages\flask\testing.py", line 34, in make_test_environ_builder
    return EnvironBuilder(path, base_url, *args, **kwargs)
  File "C:\Python3.5.1\lib\site-packages\werkzeug\test.py", line 338, in __init__
    self._add_file_from_data(key, value)
  File "C:\Python3.5.1\lib\site-packages\werkzeug\test.py", line 355, in _add_file_from_data
    self.files.add_file(key, **value)
TypeError: add_file() got an unexpected keyword argument 'name'
```
Is it really a bug or is the issue on my side?

Thanks!

**Comment by davidism** [comment]
Data describes either the raw body or form/file data.  Dump the data to a string: `data=json.dumps(request)`.
