### ISSUE TITLE
TypeError when trying to parse request with int data

### ISSUE THREAD

**Issue by Grazfather** [pallets/flask#1929]
If the `Content-Type` header is "application/json" but the `data` is a _number_ then it raises a TypeError instead of a `BadRequest`

```python
        from flask.ext.restful import reqparse, inputs
        from flask import request
        import flask
        app = flask.Flask(__name__)
        with app.test_request_context(method="post", data=b"123", content_type="application/json"):
            parser = reqparse.RequestParser()
            parser.parse_args()
```

Change the `data` from `b"123"` to `b"abc"` and you get the expected error

**Comment by ThiefMaster** [comment]
Traceback please. This might actually be raised from within Flask-RESTful which is not part of Flask itself.

**Comment by Grazfather** [comment]
Yes you might be right, sorry about that.

```======================================================================
ERROR: test_bla (test_app.AppTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/graziano/code/amazonappstore/tests/test_app.py", line 57, in test_bla
    parser.parse_args()
  File "/Users/graziano/code/amazonappstore/venv/lib/python3.5/site-packages/flask_restful/reqparse.py", line 253, in parse_args
    req.unparsed_arguments = dict(Argument('').source(req))
  File "/Users/graziano/code/amazonappstore/venv/lib/python3.5/site-packages/flask_restful/reqparse.py", line 101, in source
    values.update(value)
  File "/Users/graziano/code/amazonappstore/venv/lib/python3.5/site-packages/werkzeug/datastructures.py", line 587, in update
    for key, value in iter_multi_items(other_dict):
  File "/Users/graziano/code/amazonappstore/venv/lib/python3.5/site-packages/werkzeug/datastructures.py", line 46, in iter_multi_items
    for item in mapping:
TypeError: 'int' object is not iterable

----------------------------------------------------------------------
```

**Comment by ThiefMaster** [comment]
Yeah, looks indeed like an issue in flask-restful.

**Comment by Grazfather** [comment]
Filed flask-restful/flask-restful#598
