### ISSUE TITLE
flask app bundle with py2exe issue (AttributeError: function 'PyObject_GetBuffer' not found)

### ISSUE THREAD

**Issue by ddcatgg** [pallets/flask#1966]
With current newest version (Flask 0.11.1), there is a issue with py2exe (0.6.9).
It may be caused by flask.cli module (click 6.6).
**Flask 0.10.1 has not this issue.**

A simplest flask script named test_flask.py:

```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```

Use this py2exe script to make a test_flask.exe:

```
import sys
import py2exe
from distutils.core import setup

sys.argv.append('py2exe')

setup(
    options={
        'py2exe':
        {
            'bundle_files': 1,
        }
    },
    console=[{'script': 'test_flask.py'}],
)
```

**When execute test_flask.exe, get these:**
Traceback (most recent call last):
  File "test_flask.py", line 1, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "flask__init__.pyc", line 21, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "flask\app.pyc", line 27, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "flask\cli.pyc", line 17, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "click__init__.pyc", line 18, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "click\core.pyc", line 7, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "click\types.pyc", line 4, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "click_compat.pyc", line 530, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "click_winconsole.pyc", line 23, in <module>
  File "ctypes__init__.pyc", line 378, in **getattr**
  File "ctypes__init__.pyc", line 383, in **getitem**
AttributeError: function 'PyObject_GetBuffer' not found

My **pip list**:
alabaster (0.7.9)
Babel (2.1.1)
beautifulsoup4 (4.4.1)
blinker (1.4)
cffi (1.7.0)
click (6.6)
colorama (0.3.3)
cryptography (1.4)
cx-Oracle (5.2)
cycler (0.10.0)
Cython (0.24)
demjson (2.2.4)
docutils (0.12)
ecdsa (0.13)
enum34 (1.1.6)
erequests (0.4.1)
et-xmlfile (1.0.1)
eventlet (0.19.0)
Fabric (1.11.1)
Flask (0.11.1)
Flask-SocketIO (2.5)
greenlet (0.4.10)
idna (2.1)
ipaddress (1.0.16)
itsdangerous (0.24)
jdcal (1.2)
Jinja2 (2.8)
lxml (3.6.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
meliae (0.4.0.final.0)
MySQL-python (1.2.5)
numpy (1.11.0)
openpyxl (2.3.5)
paramiko (2.0.2)
Pillow (3.2.0)
pip (8.1.2)
psutil (4.3.0)
py2exe (0.6.9)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
Pygments (2.0.2)
pymssql (2.0.1)
pyodbc (3.0.7)
pyparsing (2.1.4)
pyserial (2.5rc2)
python-dateutil (2.5.3)
python-engineio (0.9.2)
python-socketio (1.4.2)
pytz (2016.4)
pywin32 (219)
requests (2.10.0)
setuptools (25.1.0)
six (1.10.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.9)
SQLAlchemy (1.0.8)
Twisted (16.3.0)
virtualenv (15.0.2)
Werkzeug (0.11.10)
XlsxWriter (0.8.7)
xlwt (1.1.2)
zope.interface (4.2.0)

**Comment by ddcatgg** [comment]
Why close this issue? Is it already be fixed?

**Comment by davidism** [comment]
It's an issue with Click, and there's already an open issue in Click's tracker, it's linked right above the close message.

**Comment by ddcatgg** [comment]
Okay, I got it, thanks!

**Comment by Ethan16** [comment]
good!Get the answer.
