### ISSUE TITLE
AttributeError: 'str' object has no attribute 'write' during unhandled exception logging

### ISSUE THREAD

**Issue by Miserlou** [pallets/flask#2008]
Flask + Zappa users are complaining about an error stemming from Flask's logging of exceptions.

We can reproduce this by generating an unhandled exception in a Flask application that breaks our handler's behavior, but which works for other frameworks (Django, Pyramid, etc.).

It looks like something in Flask is treating a string as if it were a stream, but I've been trying to disable all possible logging and I still see this error. I don't know what's happening. This is occurring with the Flask==0.11.1.

Here is an example:

```
[1473180521973] Traceback (most recent call last):
[1473180521973] File "/usr/lib64/python2.7/logging/init.py", line 880, in emit
[1473180521992] stream.write(fs % msg)
[1473180521992] File "/private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-RmqRtJ/Werkzeug/werkzeug/local.py", line 343, in getattr
[1473180521992] AttributeError: 'str' object has no attribute 'write'
[1473180521992] Logged from file app.py, line 1587
[1473180521992] [ERROR] 2016-09-06T16:48:41.973Z c29bebc5-7451-11e6-a6f9-bdc91c60ab58 Exception on /fail [GET]
Traceback (most recent call last):
File "/private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-KC9Xdu/flask/flask/app.py", line 1988, in wsgi_app
File "/private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-KC9Xdu/flask/flask/app.py", line 1641, in full_dispatch_request
File "/private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-KC9Xdu/flask/flask/app.py", line 1544, in handle_user_exception
File "/private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-KC9Xdu/flask/flask/app.py", line 1639, in full_dispatch_request
File "/private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-KC9Xdu/flask/flask/app.py", line 1625, in dispatch_request
File "/var/task/app.py", line 22, in fail
return 1/0
ZeroDivisionError: integer division or modulo by zero
```

Here is an example using Pyramid instead, failing as expected:
https://css89s7off.execute-api.us-east-1.amazonaws.com/dev/hello/asdf

and the same error in Flask, failing with the stream writing error:
https://pxzhirpoxd.execute-api.us-east-1.amazonaws.com/devor/fail

I am not sure what exactly is happening, and nobody in our little community has been able to figure it out either. We use Werkzeug for some middleware functionality, but since the other frameworks use this same code, I don't think this is the issue, unless there is a specific interaction between Flask and WZ, which I don't think there is.

So, I have a few theories:
    * A log handler has been configured to write to a file by default. Since Lambda is (essentially) a read-only environment, this will fail.
    * Code written for Python 3 isn't properly working in Python 2.
    * Something related to this is happening: https://github.com/pallets/flask/issues/1995

Does anybody have any ideas what might be happening here?

Related tickets and discussion:
https://github.com/Miserlou/Zappa/issues/283
https://github.com/Miserlou/Zappa/pull/302

**Comment by untitaker** [comment]
This does seem like a Werkzeug bug. Could you post the output of `pip freeze`?

**Comment by Miserlou** [comment]
Werkzeug==0.11.10

**Comment by untitaker** [comment]
To be honest I don't see anything actionable in this bugreport. I can't see a reason why, under proper usage, the `stream` used for logging would be a Werkzeug local proxy. The best thing I can advise here is to run a modified Werkzeug that prints the repr of `_get_current_object()`'s return value right here: https://github.com/pallets/werkzeug/blob/79190a5be3e3267feb5c110ffff26ff0c28e0347/werkzeug/local.py#L343 , or use pdb to debug this. Anyway I think it's too soon to say that there's any bug in Flask or Werkzeug.

**Comment by untitaker** [comment]
(BTW #1995 is unrelated as far as I can tell)

**Comment by albe-rosado** [comment]
I'm having the same error

**Comment by dacut** [comment]
Doing some cheezy print()-style debugging, things mysteriously work when I replace the call to `StreamHandler.emit()` in `ProductionHandler.emit()` with the actual method body from `StreamHandler.emit()`.

Unfortunately, it's impossible to replace the logging module since it's part of the Lambda startup environment.

Lambda definitely has some custom logging bits in there (that's how it gets it into CloudWatch, for example). I'll take a look at the AMI.

**Comment by dacut** [comment]
This turned out to be a Zappa bug, where it was initializing wsgi.errors to "" instead of a stream -- see related issue.

**Comment by untitaker** [comment]
Good to know, thanks for reporting back.
