### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by awenhu** [pallets/flask#2011]
my code:

from flask import Flask, make_response, request
app = Flask(__name__)

@app.route("/dtu/<dtuid>/<addr>", methods=["GET","OPTIONS"])
def dtu(dtuid, addr):
    o = drawMultipleDtu(dtuid,addr)
    resp = make_response(o)
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Access-Control-Request-Method"] = "POST,GET,PUT,DELETE,OPTIONS"
    resp.headers["Access-Control-Allow-Methods"] = "POST,GET,PUT,DELETE,OPTIONS"
    resp.headers["Access-Control-Allow-Headers"] = "X-Requested-With,Content-Type"

    if request.method == 'OPTIONS':
        print "it's OPTIONS"
    return resp

app.run(host="0.0.0.0", port=5010)
I always got this error:

Exception happened during processing of request from ('192.168.44.1', 54412)
----------------------------------------
Traceback (most recent call last):
  File "/mnt/ENTER/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/mnt/ENTER/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/mnt/ENTER/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/mnt/ENTER/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/mnt/ENTER/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/mnt/ENTER/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/mnt/ENTER/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by davidism** [comment]
pallets/werkzeug#954
