### ISSUE TITLE
Invalid Host header returns HTTP/500 insetad of HTTP/400

### ISSUE THREAD

**Issue by brmzkw** [pallets/flask#2106]
test.py:

```from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
```

run:

```
$> FLASK_APP=test.py flask run
 * Serving Flask app "test"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

query:

```
$> curl localhost:5000 -H "Host: '`python -c 'print \"\xbf\"'`" -i
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: text/html
Content-Length: 291
Server: Werkzeug/0.11.11 Python/2.7.12
Date: Mon, 05 Dec 2016 11:57:46 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

server log:
```
127.0.0.1 - - [05/Dec/2016 12:57:46] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/private/tmp/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/private/tmp/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/private/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/private/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 1983, in wsgi_app
    ctx = self.request_context(environ)
  File "/private/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 1944, in request_context
    return RequestContext(self, environ)
  File "/private/tmp/venv/lib/python2.7/site-packages/flask/ctx.py", line 242, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/private/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 1771, in create_url_adapter
    server_name=self.config['SERVER_NAME'])
  File "/private/tmp/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1327, in bind_to_environ
    query_args=query_args)
  File "/private/tmp/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1239, in bind
    raise BadHost()
BadHost: 400: Bad Request
```

I'm not sure if this issue should be created here or on the werkzeug repository.

Anyway, I think a HTTP/400 should be returned to the client instead of a HTTP/500.

**Comment by ThiefMaster** [comment]
`BadHost` is already a `BadRequest` subclass so unless you enabled `TRAP_HTTP_EXCEPTIONS` you should indeed get a 400 error from this. If not it's a Flask bug.

**Comment by brmzkw** [comment]
I didn't set `TRAP_HTTP_EXCEPTIONS`.

I tried to run the code with uwsgi.

```
$> cat tutu.py
from flask import Flask
app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello, World!'
```

Server:

```
 $> uwsgi --http localhost:5000 --master --module tutu --callable=app -H /tmp/venv/
*** Starting uWSGI 2.0.14 (64bit) on [Mon Dec  5 15:01:54 2016] ***
compiled with version: 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81) on 05 December 2016 14:35:14
os: Darwin-14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64
nodename: biwork
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /private/tmp/toto
detected binary path: /private/tmp/venv/bin/uwsgi
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 7168
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:58561 (port auto-assigned) fd 3
Python version: 2.7.12 (default, Jun 29 2016, 14:04:44)  [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
Set PythonHome to /tmp/venv/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f9f4bc0d900
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f9f4bc0d900 pid: 11511 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11511)
spawned uWSGI worker 1 (pid: 11512, cores: 1)
spawned uWSGI http 1 (pid: 11513)
```

(The latest stable version of uWSGI (2.0.14) and Flask (0.11.1) are installed in /tmp/venv).


client:

```
$> curl localhost:5000 -H "Host: '`python -c 'print \"\xbf\"'`" -i
curl: (52) Empty reply from server
```

server log:
```
Traceback (most recent call last):
  File "/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 1983, in wsgi_app
    ctx = self.request_context(environ)
  File "/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 1944, in request_context
    return RequestContext(self, environ)
  File "/tmp/venv/lib/python2.7/site-packages/flask/ctx.py", line 242, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/tmp/venv/lib/python2.7/site-packages/flask/app.py", line 1771, in create_url_adapter
    server_name=self.config['SERVER_NAME'])
  File "/tmp/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1327, in bind_to_environ
    query_args=query_args)
  File "/tmp/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1239, in bind
    raise BadHost()
werkzeug.exceptions.BadHost: 400: Bad Request
[pid: 11538|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 276 bytes} [Mon Dec  5 15:03:25 2016] GET / => generated 0 bytes in 3 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

I really think it's a Flask/Werkzeug bug.

**Comment by brianrusso** [comment]
Cannot replicate on 0.12.2
Example from submitter returns 200

**Comment by anotheredward** [comment]
I get this error on the example code with:
* flask 1.0.2
* python 3.6.5
* mac 10.13.4

when running
`FLASK_APP=test.py flask run`

Visiting `localhost:5000` returns a 500 Internal Server Error with no output in the console.

Visiting `127.0.0.1:5000` returns works as expected.

Is it possible that there is something about the configuration of my machine that makes this issue occur @brianrusso that you can help me find?

I'm not sure where to find the `server logs` provided above by @brmzkw  when running the debug server.

Would love to help get this error fixed, as it's surprisingly hard to debug!

**Comment by brmzkw** [comment]
Security issue?

**Comment by davidism** [comment]
I still can't reproduce this issue. Both localhost and 127.0.0.1 return a 200 response.

**Comment by anotheredward** [comment]
Is there anything I can do to help pin this error down @davidism ?

**Comment by anotheredward** [comment]
I'm using pipenv. Here's my pipfile.lock, if that might help?
```json
{
    "_meta": {
        "hash": {
            "sha256": "8ec50e78e90ad609e540d41d1ed90f3fb880ffbdf6049b0a6b2f1a00158a3288"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "version": "==6.7"
        },
        "flask": {
            "hashes": [
                "sha256:2271c0070dbcb5275fad4a82e29f23ab92682dc45f9dfbc22c02ba9b9322ce48",
                "sha256:a080b744b7e345ccfcbc77954861cb05b3c63786e93f2b3875e0913d44b43f05"
            ],
            "index": "pypi",
            "version": "==1.0.2"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519"
            ],
            "version": "==0.24"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "markupsafe": {
            "hashes": [
                "sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
            ],
            "version": "==1.0"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {}
}
```
My hosts file is the default one that installs with OSX:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
127.0.0.1 ckan-gateway
```

I previously didn't have this issue, but I recently re-installed OSX and now I do.
My workmate does not have this issue on his machine either when running the same application.

**Comment by anotheredward** [comment]
@brmzkw Could you please tell me how you got the "server logs" in your error reports? That's something I'd like to look at on my machine as well :)

**Comment by brmzkw** [comment]
Yep. Run a docker container:

```
$> mkdir -p /tmp/test
$> cd /tmp/test
$> docker run -v `pwd`:/app -w /app --name test --rm -ti python:2.7 bash
# pip install flask
# apt-get update && apt-get install -y curl
```

On the host, add the file test.py in `/tmp/test`:

```
$> cat<<EOF > /tmp/test/test.py
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
EOF
```

From the container, launch flask:

```
# FLASK_APP=test.py flask run
```

From another shell, make a query:

```
# docker exec -ti test bash
# curl localhost:5000 -H "Host: '`python -c 'print \"\xbf\"'`" -i
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: text/html
Content-Length: 291
Server: Werkzeug/0.14.1 Python/2.7.15
Date: Mon, 21 May 2018 08:28:10 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Result from the first terminal, running flask:

```
# FLASK_APP=test.py flask run
 * Serving Flask app "test.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [21/May/2018 08:27:34] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2287, in wsgi_app
    ctx = self.request_context(environ)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2204, in request_context
    return RequestContext(self, environ)
  File "/usr/local/lib/python2.7/site-packages/flask/ctx.py", line 284, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2021, in create_url_adapter
    subdomain=subdomain)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1345, in bind_to_environ
    query_args=query_args)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1257, in bind
    raise BadHost()
BadHost: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by anotheredward** [comment]
Thanks @brmzkw .

I've run the above steps and can confirm that I'm seeing the error now.

I'm still not sure why I didn't see this Error output on my local machine, I'm guessing I configured something incorrectly.

```
curl localhost:5000 -H "Host: '`python -c 'print \"\xbf\"'`" -i
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: text/html
Content-Length: 291
Server: Werkzeug/0.14.1 Python/2.7.15
Date: Mon, 21 May 2018 23:50:48 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
root@cfde202723a5:/app# 
```

```
# FLASK_APP=test.py flask run
 * Serving Flask app "test.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [21/May/2018 23:50:48] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2287, in wsgi_app
    ctx = self.request_context(environ)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2204, in request_context
    return RequestContext(self, environ)
  File "/usr/local/lib/python2.7/site-packages/flask/ctx.py", line 284, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2021, in create_url_adapter
    subdomain=subdomain)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1345, in bind_to_environ
    query_args=query_args)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1257, in bind
    raise BadHost()
BadHost: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```
