### ISSUE TITLE
Using absolute path in FLASK_APP can't run `flask db init` cli module error

### ISSUE THREAD

**Issue by future0906** [pallets/flask#2108]
when I specify absolute path like this `D:\personal\prjs\cfblog2\cfblog2\app.py` in FLASK_APP, run `flask db init` will raise a exception:
```
Traceback (most recent call last):
  File "c:\userprograms\python35\Lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\userprograms\python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\personal\local\cfblog2\lib\site-packages\flask\__main__.py", line 15, in <module>
    main(as_module=True)
  File "D:\personal\local\cfblog2\lib\site-packages\flask\cli.py", line 479, in main
    cli.main(args=args, prog_name=name)
  File "D:\personal\local\cfblog2\lib\site-packages\flask\cli.py", line 346, in main
    return AppGroup.main(self, *args, **kwargs)
  File "D:\personal\local\cfblog2\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "D:\personal\local\cfblog2\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\personal\local\cfblog2\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\personal\local\cfblog2\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\personal\local\cfblog2\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "D:\personal\local\cfblog2\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\personal\local\cfblog2\lib\site-packages\flask\cli.py", line 229, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "D:\personal\local\cfblog2\lib\site-packages\flask\cli.py", line 210, in load_app
    rv = locate_app(self.app_import_path)
  File "D:\personal\local\cfblog2\lib\site-packages\flask\cli.py", line 90, in locate_app
    __import__(module)
ImportError: No module named 'D'
```
It seems like function `locate_app` can't handle win-style path correctly.

And also please consider using command-line arguments to specify flask startup file/module instead of using environment.

**Comment by wgwz** [comment]
@future0906 could you put together the smallest possible example that reproduces this error? i'll try to reproduce the issue on my windows system, but depending on your setup, maybe there are other sources for this error.

**Comment by future0906** [comment]
@wgwz sorry for false reported issuse.I double checked my settings.It turns out was my app.py file been move away.Still this exception message miss-lead me thought it's path/module split issue.

Anyway,thantks for testing this issue, I will close it.
