### ISSUE TITLE
ImportError: No module named minitwit

### ISSUE THREAD

**Issue by judgewooden** [pallets/flask#2112]
I am new to Flask and wanted to try out the demo.

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 478, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1094, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 316, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 209, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 89, in locate_app
    __import__(module)
ImportError: No module named minitwit

```

**Comment by wgwz** [comment]
One thing is that it you're not using a virtualenv, this is the recommended situation: this is not the problem here but it will make debugging easier for you. I'm assuming you `git clone` the flask project and `cd` into `examples/minitwit`. Then I guess you run `pip install -e .`. Then `export FLASK_APP=minitwit`. I think the issue is probably you were missing `pip install -e .`, it's missing from the README and should be there. But if you follow that procedure it should work.

**Comment by judgewooden** [comment]
Thanks - That is exactly what was missing.
