### ISSUE TITLE
Socketserver problem in Python 3.6

### ISSUE THREAD

**Issue by andre2** [pallets/flask#2128]
In python 3.6 Flask can't run and return error:

> Traceback (most recent call last):
  File "D:\enviroments\flask\lib\site-packages\werkzeug\serving.py", line 65, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:/Users/User/Desktop/Blueprints/main.py", line 25, in <module>
    application.run()
  File "D:\enviroments\flask\lib\site-packages\flask\app.py", line 827, in run
    from werkzeug.serving import run_simple
  File "D:\enviroments\flask\lib\site-packages\werkzeug\serving.py", line 68, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn'

**Comment by davidism** [comment]
Already reported against Werkzeug: pallets/werkzeug#999
