### ISSUE TITLE
How to sovle the error:KeyError: 'socketio'`

### ISSUE THREAD

**Issue by JulyUp** [pallets/flask#2137]
When I run the 5th command 'flask run' for example/flaskr. It shows error
`* Serving Flask-SocketIO app "flaskr"
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 9, in <module>
    load_entry_point('Flask==0.13.dev0', 'console_scripts', 'flask')()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 507, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 374, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/cli.py", line 58, in run
    run_server()
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/cli.py", line 50, in run_server
    socketio = app.extensions['socketio']
KeyError: 'socketio'`
How to solve this problem? Thankyou very much!

**Comment by davidism** [comment]
Flask's examples do not include Flask-SocketIO. Perhaps you meant to report this there?

**Comment by wgwz** [comment]
Might also be an issue with environment, maybe not using virtualenv.

On Sunday, January 1, 2017, David Lord <notifications@github.com> wrote:
> Flask's examples do not include Flask-SocketIO. Perhaps you meant to
report this there?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/7Qv-glLM-trbd90DZeZoVK4TTCBULmkNcBojFrSIAcy7DWjQCqa66w0FPuEQHRI-olAgbASKvVPb80HNKEBkgK9XKdm3h4HUkfnslIa30vkrLp_6U7_gF5Qj-4oogphAZJRhmYRTY_jI9JrPRDPd4-f7n-NZHQ=s0-d-e1-ft#https://github.com/notifications/beacon/AJpsctyMe6yWn-53XVNaQl8zqMIyYO2nks5rN8XQgaJpZM4LYrxN.gif>

**Comment by JulyUp** [comment]
Is virtualenv nessesary?

**Comment by ThiefMaster** [comment]
It's highly recommended. Installing all those packages globally in your system not only requires you to install them as root but also adds lots of clutter to your system. With a virtualenv you have them "bundled" with your application and can easily have different versions for different applications, or reinstall them if needed, etc.

**Comment by JulyUp** [comment]
@wgwz  @ThiefMaster  It can run rightly as you said in a virtualenv. But Flaskr does not have user register function. Is there a example include user  register function in this 'pallets/flask'?

**Comment by untitaker** [comment]
@JulyUp Many people follow the (not official) tutorials by @miguelgrinberg for advanced examples.
