### ISSUE TITLE
KeyError problem 

### ISSUE THREAD

**Issue by pythonanonuser** [pallets/flask#2161]
I'm trying to start the extremely basic flask application noted here: http://flask.pocoo.org/docs/0.12/quickstart/

When I try to run "flask run" however I get the following error 

```
 * Serving Flask-SocketIO app "hello"
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    load_entry_point('Flask', 'console_scripts', 'flask')()
  File "/home/rohan/flask/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/home/rohan/flask/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/cli.py", line 58, in run
    run_server()
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/cli.py", line 50, in run_server
    socketio = app.extensions['socketio']
KeyError: 'socketio'
```

I've tried installing Flask via pip as well as from source, and verified that all the dependencies are installed. If I use the `app.run()` command in `main` it works fine, but I'd like to use `flask run` after exporting the program name but it doesn't seem to work. I've followed the instructions exactly from the website. Any advice?

**Comment by ThiefMaster** [comment]
`pip uninstall flask-socketio` - apparently `Flask-SocketIO` [hijacks][1] `flask run` but doesn't handle an app that does not use the extension nicely.

[1]: https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/setup.py#L29

**Comment by ThiefMaster** [comment]
Looks like this got [fixed][1], so upgrading Flask-SocketIO using `pip install -U flask-socketio` should also fix your problem.

[1]: https://github.com/miguelgrinberg/Flask-SocketIO/commit/7af6740b8332e65b49b065ab458a1deec73f0b2f

**Comment by ThiefMaster** [comment]
Unrelated: You really shouldn't install any flask  stuff globally on your system. Use virtualenvs instead to keep the python stuff separated between projects and from system-wide stuff.

**Comment by pythonanonuser** [comment]
Thank you! That worked.
