### ISSUE TITLE
GAE not displaying error messages for 0.12

### ISSUE THREAD

**Issue by jalexvig** [pallets/flask#2162]
When I use Flask 0.12 in my Google App Engine project I get no error messages. So a function that might throw an error would result in a log like:

```
INFO     2017-01-29 00:03:05,820 sdk_update_checker.py:229] Checking for updates to the SDK.
INFO     2017-01-29 00:03:06,428 api_server.py:205] Starting API server at: http://localhost:54929
INFO     2017-01-29 00:03:06,432 dispatcher.py:197] Starting module "default" running at: http://127.0.0.1:8080
INFO     2017-01-29 00:03:06,434 admin_server.py:116] Starting admin server at: http://localhost:8000
INFO     2017-01-29 00:03:10,212 module.py:787] default: "GET / HTTP/1.1" 500 291
INFO     2017-01-29 00:03:11,711 module.py:787] default: "GET /favicon.ico HTTP/1.1" 404 233
```

whereas when I downgrade to Flask 0.11.1 I actually get the error messaging I've come to know and love:

```
INFO     2017-01-28 23:58:06,986 sdk_update_checker.py:229] Checking for updates to the SDK.
INFO     2017-01-28 23:58:07,234 api_server.py:205] Starting API server at: http://localhost:54720
INFO     2017-01-28 23:58:07,238 dispatcher.py:197] Starting module "default" running at: http://127.0.0.1:8080
INFO     2017-01-28 23:58:07,240 admin_server.py:116] Starting admin server at: http://localhost:8000
ERROR    2017-01-28 23:58:11,804 app.py:1587] Exception on / [GET]
Traceback (most recent call last):
  File "/Users/alex/yphh/petition_companies/lib/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alex/yphh/petition_companies/lib/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alex/yphh/petition_companies/lib/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alex/yphh/petition_companies/lib/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/yphh/petition_companies/lib/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alex/yphh/petition_companies/main.py", line 70, in index
    1 / 0
ZeroDivisionError: integer division or modulo by zero
INFO     2017-01-28 23:58:11,821 module.py:787] default: "GET / HTTP/1.1" 500 291
INFO     2017-01-28 23:58:13,100 module.py:787] default: "GET /favicon.ico HTTP/1.1" 404 233
```

Aside from the traceback the two are the same.

**Comment by brianrusso** [comment]
Cannot replicate on GAE
/fail endpoint does a divide by zero and the stacktrace correctly shows up when using the gcloud log command.

```
2017-05-22 23:16:19 default[20170522t155304]  "GET /" 200
2017-05-22 23:16:51 default[20170522t160846]  [2017-05-22 23:16:51,079] ERROR in app: Exception on /fail [GET]
2017-05-22 23:16:51 default[20170522t160846]  Traceback (most recent call last):    File "/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app      response = self.full_dispatch_request()    File "/env/lib/python3.5/s
ite-packages/flask/app.py", line 1614, in full_dispatch_request      rv = self.handle_user_exception(e)    File "/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception      reraise(exc_type, exc_value, tb) 
   File "/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise      raise value    File "/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request      rv = self.dispatch_request()    File "/
env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request      return self.view_functions[rule.endpoint](**req.view_args)    File "/home/vmagent/app/main.py", line 31, in fail      return str(3/0)  ZeroDivisionError
: division by zero
2017-05-22 23:16:51 default[20170522t160846]  ERROR:root:An error occurred during a request.
```

**Comment by jeffwidman** [comment]
@brianrusso Just wanted to say thanks for your hard work on testing whether all these old tickets are still valid. Really, really appreciated.
