### ISSUE TITLE
Issue with installing app debugger

### ISSUE THREAD

**Issue by JLinthorst** [pallets/flask#2194]
I tried to install the app debugger, to make my webapp run instantly when I change the code, with:
app.run(debug=True)

However, I get the Error message below. Does someone know how to fix this?
Many thanks!

```pythontb
* Restarting with stat
* Debugger is active!
* Debugger pin code: xx
Exception in thread Thread-1:
Traceback (most recent call last):
 File "C:\Users\josep\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
   self.run()
 File "C:\Users\josep\Anaconda3\lib\threading.py", line 862, in run
   self._target(*self._args, **self._kwargs)
 File "C:\Users\josep\Anaconda3\lib\site-packages\werkzeug\serving.py", line 656, in i
   fd=fd)
 File "C:\Users\josep\Anaconda3\lib\site-packages\werkzeug\serving.py", line 550, in m
   passthrough_errors, ssl_context, fd=fd)
 File "C:\Users\josep\Anaconda3\lib\site-packages\werkzeug\serving.py", line 462, in _
   socket.SOCK_STREAM)
 File "C:\Users\josep\Anaconda3\lib\socket.py", line 450, in fromfd
   nfd = dup(fd)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by alexpantyukhin** [comment]
What is the python version do you use?

**Comment by aaossa** [comment]
I have the same error with this code:

```python
import flask

app = flask.Flask(__name__)


@app.route("/")
def hello_world():
    return "Hello, World!"

if __name__ == '__main__':
    app.run(debug=True)
```

Traceback:

```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 184-245-196
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\site-packages\werkzeug\serving.py", line 696, in inner
    fd=fd)
  File "C:\Program Files\Python35\lib\site-packages\werkzeug\serving.py", line 590, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Program Files\Python35\lib\site-packages\werkzeug\serving.py", line 499, in __init__
    socket.SOCK_STREAM)
  File "C:\Program Files\Python35\lib\socket.py", line 450, in fromfd
    nfd = dup(fd)
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
```

Even in a virtual environment:

```
(venv) PATH>python --version
Python 3.5.2

(venv) PATH>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.3)
click (6.7)
Flask (0.12)
itsdangerous (0.24)
Jinja2 (2.9.5)
MarkupSafe (1.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
setuptools (34.3.2)
six (1.10.0)
Werkzeug (0.12)
wheel (0.29.0)

(venv) PATH>python demo.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 196-189-207
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\program files\python35\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\program files\python35\Lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Tonino\Desktop\GITHUB~1\IIC223~1\venv\lib\site-packages\werkzeug\serving.py", line 696, in inner
    fd=fd)
  File "C:\Users\Tonino\Desktop\GITHUB~1\IIC223~1\venv\lib\site-packages\werkzeug\serving.py", line 590, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Users\Tonino\Desktop\GITHUB~1\IIC223~1\venv\lib\site-packages\werkzeug\serving.py", line 499, in __init__
    socket.SOCK_STREAM)
  File "c:\program files\python35\Lib\socket.py", line 450, in fromfd
    nfd = dup(fd)
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
```


It seems like something changed in Flask or Werkzeug recently.
