### ISSUE TITLE
Can't start in debug mode.

### ISSUE THREAD

**Issue by NileshPS** [pallets/flask#2200]
```
 * Serving Flask-SocketIO app "app"
 * Forcing debug mode on
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 256-225-104
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/cli.py", line 56, in run_server
    return run_command()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 432, in run_command
    use_debugger=debugger, threaded=with_threads)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 706, in run_simple
    reloader_type)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/_reloader.py", line 257, in run_with_reloader
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
  File "/usr/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

```

**Comment by NileshPS** [comment]
Works fine if i unset FLASK_DEBUG env variable.

**Comment by davidism** [comment]
You appear to be using Flask-SocketIO, not Flask.

**Comment by NoelCarlton** [comment]
hi @davidism man, i got the same issue, what command arg --`--no-reload` does? After used this my web went well.
All what i did is this: [ http://flask.pocoo.org/docs/1.0/tutorial/factory/ ]( http://flask.pocoo.org/docs/1.0/tutorial/factory/ )
