### ISSUE TITLE
EOFError during GET request due to broken session file.

### ISSUE THREAD

**Issue by Nexolight** [pallets/flask#2216]
I get this error in my logs from time to time and the only solution is to restart the server. I have no idea from where it comes but I assume this is a flask internal issue.

```
2017-03-20 18:42:17,346 ERROR    xposed.xposed_main                            Exception on /serverstats [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python3.4/dist-packages/flask_session/sessions.py", line 355, in save_session
    total_seconds(app.permanent_session_lifetime))
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/contrib/cache.py", line 762, in set
    self._prune()
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/contrib/cache.py", line 715, in _prune
    expires = pickle.load(f)
EOFError: Ran out of input

```

**Comment by Nexolight** [comment]
Deleting the session files does help.
The server does restart from time to time and might terminate the process what probably could lead to those EOFErrors.

Anyway flask should handle this error by just deleting the session. It's not a big deal, doesn't happen often.

**Comment by ThiefMaster** [comment]
`flask_session` is a third-party extension and not part of Flask.

Of course nothing should break after an exception raised from `save_session`, so if it breaks Flask and not just whatever WSGI container you are using this could indeed be a Flask bug.
