### ISSUE TITLE
CLI silences ImportError

### ISSUE THREAD

**Issue by chuckyz** [pallets/flask#2246]
Environment (CentOS 7 Vagrant in Virtualbox on Windows 10):
```
[vagrant@localhost flaskr]$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[vagrant@localhost flaskr]$ python --version
Python 2.7.5
[vagrant@localhost flaskr]$ pip freeze | grep -i flask
Flask==0.12
flaskr==0.0.0
```

I was following the flask tutorial and could not get `initdb` to show up.  Upon randomly trying the flaskr.py script I received the following:

```
[vagrant@localhost flaskr]$ python flaskr/flaskr.py
Traceback (most recent call last):
  File "flaskr/flaskr.py", line 3, in <module>
    from flask import Flask, request, session, g, redirect, url_for, abord, \
ImportError: cannot import name abord
```

When `flask` is run with the proper export statements here is the output:

```
[vagrant@localhost flaskr]$ flask
Usage: flask [OPTIONS] COMMAND [ARGS]...

  This shell command acts as general utility script for Flask applications.

  It loads the application configured (through the FLASK_APP environment
  variable) and then provides commands either provided by the application or
  Flask itself.

  The most useful commands are the "run" and "shell" command.

  Example usage:

    $ export FLASK_APP=hello.py
    $ export FLASK_DEBUG=1
    $ flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  run    Runs a development server.
  shell  Runs a shell in the app context.
```

I found this out by trying to get the shell to run to see if I could just find the init_db() function through the flask shell.

```
[vagrant@localhost flaskr]$ flask shell
Usage: flask shell [OPTIONS]

Error: The file/path provided (flaskr) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH
, ensure the extension is .py
```

Immediately upon fixing the spelling error, I was able to access `flask initdb`.

I searched through the open and closed errors and could not find this exact thing.  It simply seems unclear, and might be nice to bubble up errors to the flask CLI like the above.

**Comment by ThiefMaster** [comment]
I think this has been fixed recently. Can you try it with the git version of flask?

**Comment by chuckyz** [comment]
Wow!  Fast response. :)

That works, btw

```
[vagrant@localhost flaskr]$ flask --version
Flask 0.13-dev
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
[vagrant@localhost flaskr]$ flask
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/cli.py", line 368, in list_commands
    rv.update(info.load_app().cli.list_commands(ctx))
  File "/usr/lib/python2.7/site-packages/flask/cli.py", line 240, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/lib/python2.7/site-packages/flask/cli.py", line 98, in locate_app
    ' the app (%s):\n%s' % (module, stack_trace))
NoAppException: There was an error trying to import the app (flaskr):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/cli.py", line 91, in locate_app
    __import__(module)
  File "/vagrant/flaskr/flaskr/__init__.py", line 1, in <module>
    from .flaskr import app
  File "/vagrant/flaskr/flaskr/flaskr.py", line 3, in <module>
    from flask import Flask, request, session, g, redirect, url_for, abord, \
ImportError: cannot import name abord

Usage: flask [OPTIONS] COMMAND [ARGS]...

  This shell command acts as general utility script for Flask applications.

  It loads the application configured (through the FLASK_APP environment
  variable) and then provides commands either provided by the application or
  Flask itself.

  The most useful commands are the "run" and "shell" command.

  Example usage:

    $ export FLASK_APP=hello.py
    $ export FLASK_DEBUG=1
    $ flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  run    Runs a development server.
  shell  Runs a shell in the app context.
```

For anyone else walking through the tutorial that might run across this here's how you can easily install the git version through pip:

`pip install git+git://github.com/pallets/flask.git`

Thanks @ThiefMaster !
