### ISSUE TITLE
Bad interaction between flask.json.load() and werkzeug LimitedStream

### ISSUE THREAD

**Issue by flexo** [pallets/flask#2390]
### Expected Behavior

I expected to be able to hand flask.request.stream to flask.json.load() in order to get a Python object back. flask.request.stream provides a bytes interface which the built-in python module doesn't like (it wants string) and the flask.json module has a couple of bits of code to work around this, so I expected it to work.

See attached file (reproduced here: https://gist.github.com/flexo/5cf4fde37f7b066fb6c7a77cb7416883 )
[test.py.zip](https://github.com/pallets/flask/files/1098240/test.py.zip)

### Actual Behavior

An exception is raised because LimitedStream has no 'readable' attribute. Possibly this makes it a bug in Werkzeug rather than Flask but since Flask provided the json module I thought it'd be best to report it here first.

```pytb
Traceback (most recent call last):
  File "[...]/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "[...]/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "[...]/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "[...]/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "[...]/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "[...]/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "[...]/test.py", line 31, in errors
    data = json.load(request.stream)
  File "[...]/venv/lib/python3.5/site-packages/flask/json.py", line 154, in load
    fp = _wrap_reader_for_text(fp, kwargs.pop('encoding', None) or 'utf-8')
  File "[...]/venv/lib/python3.5/site-packages/flask/json.py", line 37, in _wrap_reader_for_text
    fp = io.TextIOWrapper(io.BufferedReader(fp), encoding)
AttributeError: 'LimitedStream' object has no attribute 'readable'
```

### Environment

* Python version: 3.5.3
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by davidism** [comment]
PRs welcome.

**Comment by flexo** [comment]
For Flask or Werkzeug?

**Comment by davidism** [comment]
Oh, thought this was on the Werkzeug tracker. Probably Werkzeug.

I need to find a reference, but there might be some other attributes that `LimitedStream` should support to look more "file-like". Seem to remember a trivia question from PyCon 2016 about it. You don't have to do that if you don't want though.
