### ISSUE TITLE
Flaskr example code RuntimeError

### ISSUE THREAD

**Issue by alexander-jiang** [pallets/flask#2413]
### Expected Behavior

The flaskr example code (in examples/flaskr) should work off-the-shelf. But I was able to reproduce the following issue by forking a clean copy of the repository and following the instructions in the README.md of the flaskr example. Namely, these are the commands I'm executing:

```
$ git clone https://github.com/alexander-jiang/flask.git
$ cd flask/examples/flaskr
$ virtualenv venv
$ venv\Scripts\activate
$ pip install -e .
$ set FLASK_APP=flaskr.factory:create_app()
$ flask initdb
$ flask run
```

### Actual Behavior

The `flask initdb` command fails with a `RuntimeError`:
```pytb
Traceback (most recent call last):
  File "c:\users\xxxxxxxxx\appdata\local\programs\python\python36-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxxxxxxxx\appdata\local\programs\python\python36-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxxxxxx\flask\examples\flaskr\venv\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\flask\cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\flask\cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\click\core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\click\core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\flask\cli.py", line 351, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\flask\cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "c:\users\xxxxxxxxx\flask\examples\flaskr\venv\lib\site-packages\flask\cli.py", line 109, in locate_app
    % module)
RuntimeError: Failed to find application in module "flaskr.factory"
```

### Environment

* OS: Windows 10 (64 bit)
* Python version: 3.6.1
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by davidism** [comment]
Flaskr's setup.py installs Flask from PyPI. If you want to test Flaskr with the dev version you cloned, you need to install that first.

```
git clone ...
cd flask
pip install -e .
now the flaskr stuff
```

**Comment by alexander-jiang** [comment]
@davidism Sorry about the false alarm, then. I didn't realize that this was already in Flask 0.13 (I'm using Flask 0.12 for a side project right now and found this error while working on that). I tried testing Flaskr with 0.13 as follows:
```
$ git clone https://github.com/alexander-jiang/flask.git
$ cd flask
$ pip install -e .
$ set FLASK_APP=flaskr.factory:create_app()
$ cd examples/flaskr
$ flask initdb
```
But now the `flask initdb` command fails with:
```
Error: No such command "initdb".
```

Am I missing something else here?

**Comment by davidism** [comment]
Now you didn't `pip install -e .` from the flaskr dir.

**Comment by alexander-jiang** [comment]
You're right; running `pip install -e .` again in the flaskr directory makes it work. Thanks!

**Comment by chuck-bass** [comment]
It's quite strange. I met the same problem.But the solution seems doesn't work.Don't know what's wrong.
`$git clone....`
`$cd flask`
`$export FLASK_APP="flaskr.factory:create_app()"`
`$cd examples/flaskr`
`$pip install -e .`
`$flask initdb`

The flask initdb command also fails with a RuntimeError.

Environment:
linux centos7.3
Python version: 2.7.5
Flask version: 0.12.2

**Comment by davidism** [comment]
As stated above, you need to install flask from source, then the example from source. You only installed the example.
