### ISSUE TITLE
Apps importing grequests crash when a restart/reload is attempted

### ISSUE THREAD

**Issue by bpaterni** [pallets/flask#2460]
### Expected Behavior

Flask apps run in debug mode (importing grequests) should reload when filesystem changes are detected.

### Actual Behavior

Instead, the following app crashes as changes are introduced and an app reload is attempted. Oddly enough, if the app is started with grequests commented out, and then uncommented, reloads process successfully.

```python
import flask              

import grequests          
import sys                

app = flask.Flask(__name__)                          
app.debug = True          

@app.route('/syspath')    
def syspath():            
    return '\n'.join(sys.path) + '\n'       
```

```
$ FLASK_APP=demo.py FLASK_DEBUG=1 flask run --host=0.0.0.0
 * Serving Flask app "demo"                          
 * Forcing debug mode on                             
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)                                                 
 * Restarting with stat                              
 * Debugger is active!                               
 * Debugger PIN: 313-109-065                         
 * Detected change in '/home/bpaterni/usr/local/src/python/flask-app-restart-demo/demo.py', reloading     
 * Restarting with stat                              
Traceback (most recent call last):                   
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/bin/flask", line 11, in <module>                
    sys.exit(main())                                 
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/flask/cli.py", line 513, in main                                                                                              
    cli.main(args=args, prog_name=name)              
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/flask/cli.py", line 380, in main                                                                                              
    return AppGroup.main(self, *args, **kwargs)      
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/click/core.py", line 697, in main                                                                                             
    rv = self.invoke(ctx)                            
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/click/core.py", line 1066, in invoke                                                                                          
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                               
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/click/core.py", line 895, in invoke                                                                                           
    return ctx.invoke(self.callback, **ctx.params)   
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/click/core.py", line 535, in invoke                                                                                           
    return callback(*args, **kwargs)                 
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func                                                                                    
    return ctx.invoke(f, obj, *args[1:], **kwargs)   
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/click/core.py", line 535, in invoke                                                                                           
    return callback(*args, **kwargs)                 
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/flask/cli.py", line 438, in run_command                                                                                       
    use_debugger=debugger, threaded=with_threads)    
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/werkzeug/serving.py", line 737, in run_simple                                                                                 
    reloader_type)                                   
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/werkzeug/_reloader.py", line 265, in run_with_reloader                                                                        
    sys.exit(reloader.restart_with_reloader())       
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/werkzeug/_reloader.py", line 124, in restart_with_reloader                                                                    
    close_fds=False)                                 
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/gevent/subprocess.py", line 234, in call                                                                                      
    with Popen(*popenargs, **kwargs) as p:           
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/gevent/subprocess.py", line 554, in __init__                                                                                  
    restore_signals, start_new_session)              
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/gevent/subprocess.py", line 1160, in _execute_child                                                                           
    self.pid = fork_and_watch(self._on_child, self._loop, True, fork)                                     
  File "/home/bpaterni/usr/local/src/python/venvs/venv-01/lib/python3.5/site-packages/gevent/os.py", line 375, in fork_and_watch                                                                                    
    watcher = loop.child(pid, ref=ref)               
  File "gevent.libev.corecext.pyx", line 518, in gevent.libev.corecext.loop.child (src/gevent/libev/gevent.corecext.c:7601)                                                                                         
  File "gevent.libev.corecext.pyx", line 1886, in gevent.libev.corecext.child.__init__ (src/gevent/libev/gevent.corecext.c:21676)                                                                                   
TypeError: child watchers are only available on the default loop
```

### Environment

* Python version: 3.5.4
* Flask version: 0.12.2
* Werkzeug version: 0.12.2
* grequests: 0.3.0
* gevent version: 1.2.2
* Click version: 6.7

**Comment by RonnyPfannschmidt** [comment]
grequests monkeypatches around all kinds of system modules in python,

as you can see the exception happens because werkzeug uses the working os module of python itself and in the traceback there is the "broken" one from gevent

im wondering if importing grequests before flask and werkzeug can elevate the issue (as then the monkeypatches would happen before werkzeug imports the modules

please try and report back

**Comment by bpaterni** [comment]
Rats! Unfortunately, importing grequests before flask did nothing as the same traceback is given on reload.

```
import grequests
import sys

import flask
...
```

**Comment by adamrt** [comment]
Downgrade to gevent 1.0.2. Ran across the advice here and it worked. https://medium.com/@kelsey88/typeerror-child-watchers-are-only-available-on-the-default-loop-36775fcbcba6

**Comment by bpaterni** [comment]
I'm assuming you're using python2, as gevent 1.0.2 does not seem compatible with my python 3 app? Installing via pip results in SyntaxErrors thrown on gevent's python2-based exception handling. I also tried downloading the gevent souce, but the build step fails due to a file not found error in compilation of `gevent/gevent.core.c`

**Comment by davidism** [comment]
I can't reproduce this with the example given. Using the latest releases of Flask, Werkzeug, and grequests.
