### ISSUE TITLE
Command to set FLASK_APP variable in flask/examples/flasker README is not compatible with released version of Flask(0.12.2)

### ISSUE THREAD

**Issue by prasadghagare** [pallets/flask#2461]
### Expected Behavior
In README of the example of flask/examples/flasker has following step to set  FLASK_APP env variable:
**export FLASK_APP=flaskr.factory:create_app()**

Next step is to initialize the DB:
And it should produce output as follows:
**Initialized the database.**

### Actual Behavior

This method to set FLASK_APP env is not compatible with the current released version of flask.
If set this way following error is observed while running next step "flask initdb":
RuntimeError: Failed to find application in module "flaskr.factory".

The issue is resolved in master branch. Still, this being starting example for many people, should be corrected.

```pytb
flask initdb
Traceback (most recent call last):
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/flask/cli.py", line 351, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/Users/prasadghagare/Desktop/projects/repo/.my_env/lib/python2.7/site-packages/flask/cli.py", line 109, in locate_app
    % module)
RuntimeError: Failed to find application in module "flaskr.factory"
```

### Environment

* Python version: 2.7.13
* Flask version: 0.12.2
* Werkzeug version: 0.7

**Comment by bryancjacobs** [comment]
I'm currently seeing this issue too.  What is the recommended solution to this problem?

**Comment by davidism** [comment]
Use the same tag in the repository as the version of the docs you're reading / version you have installed. You're looking at the dev version right now.
