### ISSUE TITLE
flask thread is always running, can't stop

### ISSUE THREAD

**Issue by 0953** [pallets/flask#2474]
### flask thread is always running, can't stop
I use flask as http server, for Multi-threaded support, I set `threaded=True`, The Call Stack shows every thread is running and not cancel when function finished.

![20170920194345](https://user-images.githubusercontent.com/4026598/30746348-24f4018a-9fdc-11e7-9a37-d93867813967.png)

And the memory has been growing until crashed.
![ilekf](https://user-images.githubusercontent.com/4026598/30746436-6139ae24-9fdc-11e7-98a9-8aaa6433f98e.png)

```
[2017-09-22 21:05:07,303] ERROR in app: Exception on /api [POST]
Traceback (most recent call last):
  File "D:\Program_Files\Python\Python2\lib\site-packages\flask-0.12.2-py2.7.egg\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program_Files\Python\Python2\lib\site-packages\flask-0.12.2-py2.7.egg\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program_Files\Python\Python2\lib\site-packages\flask-0.12.2-py2.7.egg\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program_Files\Python\Python2\lib\site-packages\flask-0.12.2-py2.7.egg\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program_Files\Python\Python2\lib\site-packages\flask-0.12.2-py2.7.egg\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\Workspace\python\ftp-server\code\Http_Server.py", line 37, in api
    for index in socket_map:
RuntimeError: dictionary changed size during iteration
```

### Environment

* Python version: 2.7.13
* Flask version: flask-0.12.2-py2.7.egg
* Werkzeug version: werkzeug-0.12.2-py2.7.egg

**Comment by davidism** [comment]
I can't reproduce this issue. Threads die as requests finish. Perhaps it has to do with how your IDE debugger is working? Regardless, the dev server should not be used in production. Use a production WSGI server such as uWSGI to handle multiple requests stably.
