### ISSUE TITLE
Internal error when requesting route with url-part == defaults

### ISSUE THREAD

**Issue by d3QUone** [pallets/flask#2601]
http://flask.pocoo.org/docs/0.12/api/#url-route-registrations

Getting a 5xx-error when requesting a route with defaults parameter 

### Code Example

```python
view = Blueprint("a", __name__, url_prefix="/a")

@view.route("/b", defaults={"consumer_id": "test"}, methods=["POST"])
@view.route("/b/<consumer_id>", methods=["POST"])
def check_consumers(consumer_id):
    return "consumer_id: {}".format(consumer_id)
```

---

### Expected Behavior

Send any other parameter - OK
```
curl -X POST '0.0.0.0:5500/a/b/anything'
```
```
consumer_id: anything
```
Send parameter == default one
```
curl -X POST '0.0.0.0:5500/a/b/test'
```
```
consumer_id: test
```

---

### Actual Behavior

Send parameter == `defaults` and get an internal error
```
curl -X POST '0.0.0.0:5500/a/b/test' -vvv
```
```
* Hostname was NOT found in DNS cache
*   Trying 0.0.0.0...
* Connected to 0.0.0.0 (127.0.0.1) port 5500 (#0)
> POST /a/b/test HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 0.0.0.0:5500
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 0.0.0.0 left intact
curl: (52) Empty reply from server
```

Traceback:
```pytb
Note: this exception is only raised in debug mode
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1590, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1576, in raise_routing_exception
    raise FormDataRoutingRedirect(request)
FormDataRoutingRedirect: A request was sent to this URL (http://0.0.0.0:5500/a/b/test) but a redirect was issued automatically by the routing system to "http://0.0.0.0:5500/a/b".  Make sure to directly send your POST-request to this URL since we can't make browsers or HTTP clients redirect with form data reliably or without user interaction.
```

---

### Environment

* Python version: 2.7.6
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
This is mostly a Werkzeug behavior. By design, a URL containing a default value will redirect to its simpler form, and Werkzeug uses a 301 redirect. 301 redirects don't preserve form data (307 redirects probably weren't commonly supported when this code was written).

The quick fix is to not have the default route, or to write your own that issues a 307 redirect.

```python
@bp.route('/b', methods=('GET', 'POST'))
def default_check_consumers():
    return redirect(url_for('.check_consumers', id=1), code=307)
```

**Comment by davidism** [comment]
Alternatively, while it makes some sense to show a default id on GET requests, it doesn't make as much sense to send POST data to a default, I'd always want to see a specific id being posted to.

Change the default route to only be for GET, and it works.

```python
@bp.route('/b', defaults={'id': 1})
@bp.route('/b/<int:id>', methods=('GET', 'POST'))
```

**Comment by d3QUone** [comment]
@davidism thank you for fast reply! I guess there are several possible solutions in this case:
* add an issue in Werkzeug's project
* add a description of this behaviour in Flask documentation and/or possible issues

**Comment by davidism** [comment]
If you have time and can document that a default value redirects to the simpler route, and that this affects POST requests, that would be great!

It may also be good to have Werkzeug use 307 instead, so an issue there would be good. It's mostly down to figuring out what browsers support it.

**Comment by rochacbruno** [comment]
You can also set `redirect_defaults` to false

**Comment by rochacbruno** [comment]
```
`defaults`
    An optional dict with defaults for other rules with the same endpoint.
    This is a bit tricky but useful if you want to have unique URLs::

        url_map = Map([
            Rule('/all/', defaults={'page': 1}, endpoint='all_entries'),
            Rule('/all/page/<int:page>', endpoint='all_entries')
        ])

    If a user now visits ``http://example.com/all/page/1`` he will be
    redirected to ``http://example.com/all/``.  If `redirect_defaults` is
    disabled on the `Map` instance this will only affect the URL
    generation.

```
