### ISSUE TITLE
FLASK_APP factory export doesn't work when invoked with parentheses and quotations but works otherwise

### ISSUE THREAD

**Issue by ambodi** [pallets/flask#2605]
I have an app factory under a function called ```create_app```:

```python
"""Factory for flask app."""
import os
from flask import Flask

def create_app(config=None):
    """Create the app and add extra config."""
    app = Flask('mini')

    app.config.update(dict(
        DATABASE=os.path.join(app.root_path, 'mini.db'),
        DEBUG=True,
        SECRET_KEY=b'_5#y2L"F4Q8z\n\xec]/',
        USERNAME='admin',
        PASSWORD='default'
    ))

    return app
```

### Expected Behavior

I should be able to export my FLASK_APP and use that function like the following:

```
export FLASK_APP="app.factory:create_app()"
flask run 
```
### Actual Behavior

I am receiving:

```
RuntimeError: Failed to find application in module "mini.factory"
```

```pytb
Traceback (most recent call last):
  File "/Users/ara/anaconda/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ara/anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 423, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 152, in __init__
    self._load_unlocked()
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/Users/ara/anaconda/lib/python2.7/site-packages/flask/cli.py", line 109, in locate_app
    % module)
RuntimeError: Failed to find application in module "mini.factory"
```
### Workaround

I can get it to work by setting:

```
export FLASK_APP=factory.create_app
```

### Environment

```
Flask 0.12.2
Python 2.7.9 |Anaconda custom (x86_64)| (default, Dec 15 2014, 10:37:34)
[GCC 4.2.1 (Apple Inc. build 5577)]
```

**Comment by ThiefMaster** [comment]
Using `()` and providing arguments is only supported in newer flask versions (unreleased, but you can try with git master).

**Comment by ambodi** [comment]
@ThiefMaster but the tutorial for flaskr doesn't say this, right?

**Comment by ThiefMaster** [comment]
You should read the docs for the version you are using, i.e. http://flask.pocoo.org/docs/0.12/ and not http://flask.pocoo.org/docs/dev/ ;)
