### ISSUE TITLE
error in init_db()

### ISSUE THREAD

**Issue by simple321vip** [pallets/flask#2649]
I  do like that the site of "http://www.pythondoc.com/flask/tutorial/dbinit.html#tutorial-dbinit" writes,
but it shows a ValueError.
the following is my code:
+++++++++++++++++++++++++++++++++++++
Python 3.6.4 (default, Mar  4 2018, 12:03:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flaskr import init_db
>>> init_db()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saber/flaskr/flaskr.py", line 29, in init_db
    db.cursor().executescript(f.read())
ValueError: script argument must be unicode.
>>>

**Comment by RonnyPfannschmidt** [comment]
at first glance this is a unofficial outdated version not affiliated with the project
