### ISSUE TITLE
Wrong wheel for Flask 0.12.3 in PyPI

### ISSUE THREAD

**Issue by lafrech** [pallets/flask#2728]
https://pypi.org/project/Flask/0.12.3/#files

*Flask-0.12.3-py2.py3-none-any.whl* contains a `flask/json` directory.

It does not correspond to the `0.12.3` tag. Looks like it is a more recent revision.

The .tag.gz looks fine (I just checked it contains `flask/json.py` and no `flask/json` directory).

**Comment by lafrech** [comment]
I don't think the wheel even corresponds to an existing revision.

When running it, I get this error:

    AttributeError: 'Blueprint' object has no attribute 'json_encoder'

which suggests it is using `flask.json` from the 1.0 branch and `flask.Blueprint` from the 0.12 branch.

**Comment by joakimkarlsson** [comment]
It looks like make-release.py doesn't remove output from earlier builds before generating a wheel. Could it be that the json-dir is a remnant from an earlier build?

**Comment by ThiefMaster** [comment]
That's why building releases is best done from fresh git clone (or after running git-clean), especially if the build script does not contain sanity checks aborting the build in case any unexpected files are found (even if they are on gitignore).

I did [something like this](https://github.com/indico/indico/blob/master/bin/maintenance/build-wheel.py#L135-L162) in a package I maintain after I ended up with (luckily harmless) debug code in a release build (.py file that was git-excluded but of course included by the build).

**Comment by justanr** [comment]
Deploys from Travis could be set up, it pretty painless (hardest part was installing the Travis cli and that was only because I didn't have ruby installed). I have flask allows set to only deploy tagged commits from master.

**Comment by Hernrup** [comment]
+1. We are experiencing the same issue. The build looks like it might have been built from a dirty git state.

**Comment by jakul** [comment]
@davidism Can you fix this?

**Comment by dmsimard** [comment]
Also seeing this issue, it yields a stack trace that looks like this:
```
Traceback (most recent call last):
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dmsimard/dev/git/openstack/ara/ara/views/reports.py", line 208, in ajax_results
    return jsonify(results)
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/json/__init__.py", line 177, in dumps
    _dump_arg_defaults(kwargs)
  File "/home/dmsimard/dev/git/openstack/ara/.tox/py27/lib/python2.7/site-packages/flask/json/__init__.py", line 98, in _dump_arg_defaults
    bp.json_encoder if bp and bp.json_encoder
AttributeError: 'Blueprint' object has no attribute 'json_encoder'
```

**Comment by davidism** [comment]
Uh, weird. I usually inspect the wheels before uploading, sorry about that. I'll release 0.12.4 shortly.

**Comment by dmsimard** [comment]
@davidism thanks !

**Comment by davidism** [comment]
https://pypi.org/project/Flask/0.12.4/
