### ISSUE TITLE
Traceback shown when running `flask` without any args or an app

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/flask#2768]
### Expected Behavior

Only the error message / usage information being printed

### Actual Behavior

A traceback shows up above the usage information.

### Environment

* Python version: 2.7.14
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

---

```
[adrian@blackhole:/tmp]> virtualenv testenv
New python executable in /tmp/testenv/bin/python2.7
Also creating executable in /tmp/testenv/bin/python
Installing setuptools, pip, wheel...done.

[adrian@blackhole:/tmp]> ./testenv/bin/pip install flask
Collecting flask
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting Werkzeug>=0.14 (from flask)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting click>=5.1 (from flask)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from flask)
Collecting Jinja2>=2.10 (from flask)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask)
Installing collected packages: Werkzeug, click, itsdangerous, MarkupSafe, Jinja2, flask
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 flask-1.0.2 itsdangerous-0.24


[adrian@blackhole:/tmp]> ./testenv/bin/flask
Traceback (most recent call last):
  File "/tmp/testenv/lib/python2.7/site-packages/flask/cli.py", line 529, in list_commands
    rv.update(info.load_app().cli.list_commands(ctx))
  File "/tmp/testenv/lib/python2.7/site-packages/flask/cli.py", line 384, in load_app
    'Could not locate a Flask application. You did not provide '
NoAppException: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  Provides commands from Flask, extensions, and the application. Loads the
  application defined in the FLASK_APP environment variable, or from a
  wsgi.py file. Setting the FLASK_ENV environment variable to 'development'
  will enable debug mode.

    $ export FLASK_APP=hello.py
    $ export FLASK_ENV=development
    $ flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  routes  Show the routes for the app.
  run     Runs a development server.
  shell   Runs a shell in the app context.
```

**Comment by davidism** [comment]
Didn't it originally only show the error message then someone made a PR adding the traceback? I'm wary of removing the traceback, since it could contain information about import or syntax errors.

Possible duplicate of #2741?

**Comment by ThiefMaster** [comment]
Yeah, duplicate of that issue. I think the traceback makes sense if a `FLASK_APP` is set/found, but not if there's simply nothing to import.
