### ISSUE TITLE
AttributeError: 'FileWrapper' due to click

### ISSUE THREAD

**Issue by 2press** [pallets/flask#2801]
Since a few days I am facing this error when running `Flask.run()` caused by `click` on Windows 10.0.17134 with Python 3.6.5, flask 1.0.2 and click6.7:
```
Traceback (most recent call last):
  File "D:\Code\GitHub\StarCraft-Casting-Tool\scctool\tasks\webapp.py", line 189, in run
    self.application.run(port=65010)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\utils.py", line 217, in echo
    file = _default_text_stdout()
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\_compat.py", line 621, in func
    rv = wrapper_func()
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\_compat.py", line 385, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "c:\users\tasch\appdata\local\programs\python\python36-32\lib\site-packages\click\_winconsole.py", line 264, in _get_windows_console_stream
    f = getattr(f, 'buffer')
AttributeError: 'FileWrapper' object has no attribute 'buffer'
```

Can anybody help me?

**Comment by 2press** [comment]
Fixed by updating click to the latest unreleased master branch.
