### ISSUE TITLE
UnsupportedOperation: not writable utils.py, line 259, in echo  file.write(message)

### ISSUE THREAD

**Issue by gadzet** [pallets/flask#2863]
### Expected Behavior

Running this code worked previously, then i switched form code editor to spyder IDE.

```python
from flask import Flask
from flask_restful import Api
from flask_jwt import JWT

from security import authenticate, identity
from resources.user import UserRegister
from resources.product import Product, ProductList

app = Flask(__name__)
app.secret_key = 'longandcomplicated'
api = Api(app)

jwt = JWT(app, authenticate, identity)

api.add_resource(ProductList, '/products')
api.add_resource(Product, '/product/<string:name>')
api.add_resource(UserRegister, '/register')

app.run(port=5000, debug=True)

```

### Actual Behavior

Tell us what happens instead.

```pytb

runfile('D:/pEshop/code/app.py', wdir='D:/pEshop/code')
Traceback (most recent call last):

  File "<ipython-input-1-84a080c78298>", line 1, in <module>
    runfile('D:/pEshop/code/app.py', wdir='D:/pEshop/code')

  File "C:\Users\user\Anaconda3\envs\pShop\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\user\Anaconda3\envs\pShop\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/pEshop/code/app.py", line 19, in <module>
    app.run(port=5000, debug=True)

  File "C:\Users\user\Anaconda3\envs\pShop\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)

  File "C:\Users\user\Anaconda3\envs\pShop\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)

  File "C:\Users\user\Anaconda3\envs\pShop\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)

UnsupportedOperation: not writable 
```

### Environment

* Python version: 3.6.6
* Flask version: 1.0.2
* Werkzeug version: 0.14.1
### Expected Behavior

After i've commentd out the line with the error it started to work fine, but I'm not getting messages in console anymore.

**Comment by davidism** [comment]
That's an issue with Spyder's console. Apparently it's not writable by Click. Please report that to them.

**Comment by gadzet** [comment]
Solved it by replacing _default_text_stdout() to sys.stdout

```python  
if file is None:
        if err:
            file = _default_text_stderr()
        else:
            file = sys.stdout
```

**Comment by davidism** [comment]
To be clear: manually patching library code you don't control is not a good idea, as it will be wiped during an upgrade. You need to get in touch with Spyder and figure out why their console doesn't play nice with Click's output normalization.

**Comment by warkechetan** [comment]
> 
> 
> Solved it by replacing `_default_text_stdout()` to `sys.stdout`
> 
> ```python
> if file is None:
>         if err:
>             file = _default_text_stderr()
>         else:
>             file = sys.stdout
>I m getting same error from where u changed this?

**Comment by ricky10116** [comment]
> sys.stdout

Thanks, This method is working !!
