### ISSUE TITLE
Chained exceptions should be logged properly

### ISSUE THREAD

**Issue by rgabbard** [pallets/flask#2894]
### Expected Behavior

When a chained exception is thrown, the full exception chain should be logged.

```python
from flask import Flask

app = Flask(__name__)


def do_something():
  raise ValueError("Foo")


@app.route('/exception_test', methods=['GET', 'POST'])
def process():
  try:
    do_something()
  except Exception as e:
    raise ValueError("Wrapper") from e

if __name__ == '__main__':
  app.debug = True
  app.config['PROPAGATE_EXCEPTIONS'] = True
  app.run(debug=True)
```

Then `wget  http://127.0.0.1:5000/exception_test`

### Actual Behavior

Instead only the exception at the "end of the chain" is logged:

```pytb
127.0.0.1 - - [29/Aug/2018 17:18:56] "GET /exception_test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 22, in process
    raise ValueError("Wrapper") from e
ValueError: Wrapper
```

The same problem appears in the HTML stack traces.

This problem was also mentioned by @mscheper  in [this comment](https://github.com/pallets/flask/issues/2023#issuecomment-301493159)

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
If you have time, investigating why it's not logging them right now, and/or how we can fix that, would be helpful.

**Comment by mozartilize** [comment]
After took a look, I think the reason is `werkzeug.debug.tbtools.Traceback` doesn't handle `__cause__` or `__context__` of exception

**Comment by davidism** [comment]
That's the debugger, I think this is about logging. Although it would be nice for the debugger to handle that too.

**Comment by rgabbard** [comment]
The workaround @mscheper gave:

```
@app.errorhandler(Exception)
def better_exception_handler(error):
    current_app.logger.exception('Whoopsie!')
    return 'Internal server error', 500
```

works well enough for my immediate needs, so it will be a while before I can dig into this very much.

However, I do have a more minimal example:

```python
from flask import Flask

app = Flask(__name__)


def do_something():
  raise ValueError("Foo")


@app.route('/exception_test', methods=['GET', 'POST'])
def process():
  try:
    do_something()
  except Exception as e:
    raise ValueError("Wrapper") from e

if __name__ == '__main__':
  app.config['PROPAGATE_EXCEPTIONS'] = True
  app.run(debug=False)
```

Debug mode is not needed. However, `PROPAGATE_EXCEPTIONS` is - without it, the log message has the proper chaining,

**Comment by rgabbard** [comment]
@davidism : This is probably not the right fix (I don't know what consequences this change would have elsewhere) but if I take the `Traceback` object from `tbtools.py`, save the `tb` constructor argument, and then replace

```
buf = traceback.format_exception_only(self.exc_type, self.exc_value)
```

in `exception()` with

```
buf = traceback.format_exception(self.exc_type, self.exc_value, self.tb,
                                 chain=True)
``` 

then the desired output is logged.

**Comment by davidism** [comment]
Are we talking about exception logging, which comes from Flask, or the interactive traceback, which comes from the Werkzeug debugger middleware?

**Comment by rgabbard** [comment]
I'm afraid I am not familiar enough with Flask to be sure.  From my point of view as a user, when I run the example above, an exception is logged to stderr which lacks the chaining information, which sounds like what I assume Flask "exception logging" is (perhaps mistakenly).  On the other hand, the code which actually requests logging of the exception is in `werkzeug.serving` (line 287 in 1.0.2 but [here](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L294) on `master`), so maybe I should shift the issue to that project?

**Comment by rgabbard** [comment]
Ah, but this is using the development server:

```
* Serving Flask app "chained_exception_mcve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
```

so I suspect it is specific to that (which I guess is part of the werkzeug layer) and not to Flask proper.

**Comment by davidism** [comment]
You're getting confused by the other user who dug into Werkzeug. We're talking about Flask logging, nothing in Werkzeug is relevant.

Since we've gotten off track, I'll reiterate that investigating why it's not logging them right now, and/or how we can fix that, would be helpful, but I mean Flask's logging, not Werkzeug.

**Comment by rgabbard** [comment]
@davidism : I'm not sure I understand.  Currently if I run this Python script:

```
from flask import Flask

app = Flask(__name__)


def do_something():
  raise ValueError("Foo")


@app.route('/exception_test', methods=['GET', 'POST'])
def process():
  try:
    do_something()
  except Exception as e:
    raise ValueError("Wrapper") from e

if __name__ == '__main__':
  app.config['PROPAGATE_EXCEPTIONS'] = True
  app.run(debug=False)
```

and then do `wget  http://127.0.0.1:5000/exception_test`, I get

```
 * Serving Flask app "chained_exception_mcve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Aug/2018 13:02:18] "GET /exception_test HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 20, in process
    raise ValueError("Wrapper") from e
ValueError: Wrapper
```

but if I edit `tbools.py` from `werkzeug.debug` as described above, I get the desired output of:

```
 * Serving Flask app "chained_exception_mcve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Aug/2018 13:03:58] "GET /exception_test HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 20, in process
    raise ValueError("Wrapper") from e
Traceback (most recent call last):
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 18, in process
    do_something()
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 8, in do_something
    raise ValueError("Foo")
ValueError: Foo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabbard/anaconda3/envs/gaia-alternatives/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabbard/projects/gaia/gaia-alternatives/repos/vista-nlp-jvm/vista_nlp_serialization/chained_exception_mcve.py", line 20, in process
    raise ValueError("Wrapper") from e
ValueError: Wrapper
```

If I drop a breakpoint on where the logging of the exception occurs, there's actually no Flask code anywhere in the stack, only `werkzeug` code.  So it seems to me I was wrong to link this with issue #2023 and that the (to me undesirable) behavior I am seeing is due to `werkzeug` and not Flask itself.

But I am very much a Flask newbie, so there may be something I am missing.

**Comment by davidism** [comment]
`PROPAGATE_EXCEPTIONS` tells Flask to ignore the exception and pass it up the chain, to Werkzeug's dev server in this case. If this is a Werkzeug issue, it needs to be reported to Werkzeug.

If you turn off `PROPAGATE_EXCEPTIONS`, does *Flask's* logging handle the traceback correctly?

**Comment by rgabbard** [comment]
@davidism : Yes, Flask handles it correctly - I will shift the issue to Werkzeug.
