### ISSUE TITLE
Default port overrides requesting a system assigned port

### ISSUE THREAD

**Issue by Ben-RK** [pallets/flask#2926]
### Expected Behavior

When running a flask application with `app.run(port=0)`, flask should pass the '0' port down to werkzeug to use a port assigned by the operating system.

### Actual Behavior

The logic in flask/app.py:932 sets the port to the default 5000, which can cause port conflicts, which is the exact situation that setting `port=0` should avoid. This is a regression from the behaviour exhibited in prior versions.

```pytb
>>> app.run(port=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/.../lib/python3.6/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/.../lib/python3.6/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/.../lib/python3.6/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File ".../lib/python3.6/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/.../lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/.../lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/.../lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
Makes sense. Marking this as beginner friendly, I'd be happy to review a PR.

**Comment by vorelq** [comment]
Hi, I'd like to try and fix this one.

**Comment by abhi1851** [comment]
This issue occurs because `port 0` is reserved by system, use port `1025` and above (best example is` port = 5000`)

**Comment by patiencedaur** [comment]
I think it's closed

**Comment by Man-Jain** [comment]
Is this one still up for grabs ?

**Comment by ThiefMaster** [comment]
No, there's a PR for it (see above)

**Comment by Man-Jain** [comment]
Yeah but it as inactive for over a month. That's why I asked.

**Comment by theodesp** [comment]
@Man-Jain you can politely ask the PR implementor to see if he can fix the PR comments otherwise you can fork his PR and try to fix it yourself if you are in a hurry.

**Comment by davidism** [comment]
The PR is fine, I just haven't got around to merging it.

**Comment by ivonindza** [comment]
Is the fix coming any time soon? This issue forces me to use an old version.
