### ISSUE TITLE
'301' is not a recognized HTTP error code

### ISSUE THREAD

**Issue by jvannier** [pallets/flask#2927]
I just upgraded to Flask 1.0.2 and my code (which was working):

```
from http.client import MOVED_PERMANENTLY

@app.errorhandler(MOVED_PERMANENTLY)
def error_handler(err):
    print(err)
```

now fails with:
```
 mod_wsgi (pid=66451): Target WSGI script 'app.py' cannot be loaded as Python module.
 mod_wsgi (pid=66451): Exception occurred processing WSGI script 'app.py'.
 Traceback (most recent call last):
   File "app.py", line 128, in <module>
     @app.errorhandler(MOVED_PERMANENTLY)
   File "python2.7/site-packages/flask/app.py", line 1316, in decorator
     self._register_error_handler(None, code_or_exception, f)
   File "python2.7/site-packages/flask/app.py", line 66, in wrapper_func
     return f(self, *args, **kwargs)
File "python2.7/site-packages/flask/app.py", line 1349, in _register_error_handler
" HTTPException with that code instead.".format(code_or_exception)
KeyError: "'301' is not a recognized HTTP error code. Use a subclass of HTTPException with that code instead."
```

Am I doing something wrong?

**Comment by davidism** [comment]
301 is not an exception registered in `werkzeug.exceptions.default_exceptions`. While the way error handlers were registered was changed, I'm not clear how this code would ever have worked. The code that results in this error *hasn't* changed since at least 0.11.

**Comment by jvannier** [comment]
That may be my problem.... I am upgrading from 0.9

**Comment by jvannier** [comment]
So I updated the code to be

```
from werkzeug.routing import RequestRedirect

@app.errorhandler(RequestRedirect)
def error_handler(err):
    print(err)
```

But it's not catching the 301 error (and it's the same code in the same place as it was before). Ideas?
