### ISSUE TITLE
Serial port access problem in DEBUG mode.

### ISSUE THREAD

**Issue by edouin** [pallets/flask#2977]
### Expected Behavior

Sending commands through the serial port.

```python
app = Flask(__name__)
serialPort = serial.Serial(port = "COM5", baudrate=1000000,
                           bytesize=8, timeout=2, stopbits=serial.STOPBITS_ONE)

lamp = {
   1 : {'name' : 'n1', 'state' : True},
   2 : {'name' : 'n2', 'state' : True} 
}

@app.route("/")
def hello():
   templateData = {
      'lamp': lamp
      }

   
   return render_template('main.html', **templateData)


@app.route("/setPin/<action>")
def action(action):

   if action == "on":

      serialPort.write(b"n2c1111\r\n")
      lamp[1]["state"] = True

   if action == "off":
      serialPort.write(b"n2c0000\r\n")
      lamp[1]["state"] = False


   templateData = {
      'lamp': lamp
   }

   return render_template('main.html', **templateData)

if __name__ == "__main__":
   app.run(host='0.0.0.0', port=5000, debug=True)
```

### Actual Behavior

I can not access the serial port with  FLASK_ENV = development and FLASK_DEBUG = 1. Everything works fine with DEBUG mode disabled.

```pytb
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 1
In folder C:/Users/user/PycharmProjects/Ho_server
C:\Users\user\Anaconda3\python.exe -m flask run
 * Serving Flask app "app.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 138-068-963
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Oct/2018 10:49:27] "GET /setPin/on HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\user\PycharmProjects\H_server\app.py", line 8, in <module>
    bytesize=8, timeout=2, stopbits=serial.STOPBITS_ONE)
  File "C:\Users\user\Anaconda3\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\user\Anaconda3\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)
```

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2

**Comment by davidism** [comment]
The development env runs a reloader. After loading, it spawns a second thread with the actual server. You're unconditionally opening a serial port in the top level module namespace, then a new process spawns and does it again.

See https://stackoverflow.com/questions/25504149/why-does-running-the-flask-dev-server-run-itself-twice

**Comment by edouin** [comment]
Thanks! The issue is solved by adding:
```python
if os.environ.get('WERKZEUG_RUN_MAIN') == 'true':
   serialPort = serial.Serial(port="COM5", baudrate=1000000,
                              bytesize=8, timeout=2, stopbits=serial.STOPBITS_ONE)
```
