### ISSUE TITLE
Flask-Angular issue for Uploading file through api call

### ISSUE THREAD

**Issue by akshayklr057** [pallets/flask#3092]
Hi team,
For my project, I am using Flask at server side and Angular at the client side. When I call a flask API to upload a CSV file then sometimes the file gets uploaded successfully and sometimes it throws the keyError on the file name.
I am continuously facing this issue and have tried various methods to handle the header while calling the API, but no luck in that. 

```pytb
Traceback (most recent call last):
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
    return original_handler(e)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
    return original_handler(e)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\6-feb\intent-python\src\intent\incident\incidenttraining.py", line 20, in db_insert_training_tickets
    return IncidentTraining.db_insert_training_tickets(customer_id, dataset_name, team_name)
  File "D:\6-feb\intent-python\src\intent\incident\incidenttraining.py", line 41, in db_insert_training_tickets
    file = request.files['trainingData']
  File "C:\Users\deepak.saini\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\datastructures.py", line 431, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: KeyError: 'trainingData'
Error in atexit._run_exitfuncs:
```

**Comment by akshayklr057** [comment]
You can find the attached file which shows the full traceback of uploading error.

**Comment by ThiefMaster** [comment]
If `request.files['trainingData']` fails with a KeyError it means no file was uploaded in a field named trainingData. This is not a Flask bug but something related to your client-side code.

**Comment by akshayklr057** [comment]
But I have file coming with the same name from client-side.

**Comment by ThiefMaster** [comment]
Did you check your browser's dev tools to ensure the name is correct? And that it's actually a multipart-formatted request body?

I'd `print request.files` to check what keys are in there.
