### ISSUE TITLE
SOAP requests cause 500's in Flask code

### ISSUE THREAD

**Issue by ddevault** [pallets/flask#3094]
Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/lib/python3.6/site-packages/srht/flask.py", line 197, in _csrf_check
    view = "{0}.{1}".format(view.__module__, view.__name__)
AttributeError: 'NoneType' object has no attribute '__module__'
```

Request body:

```
<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns="http://microsoft.com/webservices/"><soap:Body><QueryNodes></QueryNodes></soap:Body></soap:Envelope>
```

Request headers:

```
Host: 127.0.0.1:5001
Connection: close
Content-Length: 313
Accept: */*
User-Agent: git/git-import/0.4.3
Soapaction: "http://microsoft.com/webservices/QueryNodes"
Content-Type: text/xml; charset=UTF-8
```

**Comment by ddevault** [comment]
Sorry for the noise, the bug is in my code.
