### ISSUE TITLE
Testing with TestClient and a custom response_class calls constructor twice

### ISSUE THREAD

**Issue by ekor15** [pallets/flask#3110]
When working with a custom response class the test_client calls the response class constructor, after the make_response already called the response class constructor

This causes a CustomResponse object to be passed to the constructor of the CustomResponse class.
A basic example of the problem
```python
import json
from unittest import TestCase

from flask import Response, Flask
from hamcrest import has_entry
from hamcrest.core import assert_that
from hamcrest.core.core import is_


class TestMediaAppRestResponse(TestCase):

    def setUp(self):
        self.media_app = MyApp(__name__)
        self.client = self.media_app.test_client()

    def _test_client(self):
        return self.media_app.test_client()

    def test_rest_response__dict_register_response_class_before_test_client(self):
        return_value = {'dict_prop': 'dict_value'}
        self.media_app.route('/')(_make_handler_with_response(return_value))
        self.media_app.register_response_class()

        test_client = self._test_client()

        response = test_client.get('/')
        print ('will never get here')

    def test_rest_response__dict_register_response_class_after_test_client(self):
        return_value = {'dict_prop': 'dict_value'}

        test_client = self._test_client()

        self.media_app.register_response_class()
        self.media_app.route('/')(_make_handler_with_response(return_value))

        response = test_client.get('/')
        assert_that(response.get_json(), has_entry('payload', is_(return_value)))


def _make_handler_with_response(response):
    def wrapped_handler():
        return response
    return wrapped_handler


class MyApp(Flask):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def register_response_class(self):
        self.response_class = MyResponse

    def make_response(self, response_value):
        if isinstance(response_value, self.response_class):
            return response_value
        return self.response_class(response_value, http_status=200, code=0, message='ok')


class MyResponse(Response):
    def __init__(self, payload=None, http_status: int = 200,
                 code: int = None,
                 message: str = '', *args, **kwargs):
        message = message
        code = code if code is not None else http_status
        payload = payload
        body_str = json.dumps({'code': code, 'message': message, 'payload': payload}, separators=(',', ':'))

        super().__init__(body_str, status=http_status, mimetype='application/json', *args, **kwargs)



```

### Expected Behavior

The custom response class constructor should only be called by the make_response method

### Actual Behavior

The constructor was called by the make_response method then by the test_client becuase the custom response class is passed to the client when it is created by the app. 
```pytb
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/elirans/projects/media-framework/tests/media_framework_test/http/flask/test_media_app_rest_response_multiple_calls.py", line 26, in test_rest_response__dict_register_response_class_before_test_client
    response = test_client.get('/')
  File "/Users/elirans/projects/media-framework/run/lib/python3.7/site-packages/werkzeug/test.py", line 830, in get
    return self.open(*args, **kw)
  File "/Users/elirans/projects/media-framework/run/lib/python3.7/site-packages/flask/testing.py", line 200, in open
    follow_redirects=follow_redirects
  File "/Users/elirans/projects/media-framework/run/lib/python3.7/site-packages/werkzeug/test.py", line 822, in open
    response = self.response_wrapper(*response)
  File "/Users/elirans/projects/media-framework/tests/media_framework_test/http/flask/test_media_app_rest_response_multiple_calls.py", line 72, in __init__
    body_str = json.dumps({'code': code, 'message': message, 'payload': payload}, separators=(',', ':'))
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Headers is not JSON serializable
```

### Environment

* Python version: 3.7.1
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
There is way too much non-standard code going on in this example. Please reduce it to a minimal example demonstrating that this is an issue with Flask.

**Comment by davidism** [comment]
Here's a minimal example:

```python
from flask import Flask, Response


app = Flask(__name__)


@app.route("/")
def index():
    return "Hello, World!"


class CustomResponse(Response):
    def __init__(self, *args, **kwargs):
        print("CustomResponse")
        super().__init__(*args, **kwargs)


app.response_class = CustomResponse
client = app.test_client()
rv = client.get("/")
print(rv.get_data(as_text=True))
```

Output:

```
CustomResponse
CustomResponse
Hello, World!
```

**Comment by davidism** [comment]
The arguments passed to `Response.__init__` must still work the same as Werkzeug expects (duck typing), but you've changed that to pass arbitrary values then process them without checking what was passed first. The processing you're doing in `CustomResponse.__init__` should be moved to `MyApp.make_response`. `make_response` should still construct the `Response` by passing it a string or iterable.

The reason why is that internal code besided your own expects `response_class` to have the same interface as the default. Flask will use `response_class` to generate the response from the value returned by the view. Werkzeug's `Client` runs the Flask app as if it were a WSGI server, the response it gets is the WSGI response that the `response_class` produces, a tuple of . Flask tells the client to wrap that raw response in its response class so that the return value is easier to work with.

**Comment by ekor15** [comment]
First, thank you very much for the quick response. I want to make sure that I explained myself correctly

The problem is only in testing because of the behavior of the test client.
I will give this example: I want to return MyResponse object from the handler for some reason (headers for example)

```python
import json
from flask import Flask, Response
app = Flask(__name__)

@app.route("/")
def index():
    return MyResponse("Hello, World!", headers={'x-some-header': 'header value'})

class MyResponse(Response):
    def __init__(self,response, *args, **kwargs):
        print("CustomResponse")
        response = '{"code":0,"payload":"' + json.dumps(response) + '"}'
        super().__init__(response,*args, **kwargs)

if __name__ == '__main__':
    # creating a client before registering the custom response - this works like an external client calling the server
    client = app.test_client()
    app.response_class = MyResponse
    rv = client.get("/")
    print('works like it would in production: ' + rv.get_data(as_text=True))

    # this client has the response wrapper.
    client = app.test_client()
    rv = client.get("/")
    print('will not get here' + rv.get_data(as_text=True))
```


* This handler will work in production. This is just a test_client problem
* This will happen regardless if I return a MyResponse object from the handler
    As you mentioned - override the make_response to return an instance of MyResponse will still cause this bug.
3. I do not want to wrap my return value in the handlers. If I reuse this code in a project that has a different wrapper or does not have a wrapper for the response

Do you still think this is not a bug?

**Comment by ekor15** [comment]
Hi @davidism 
Can you please respond to my new comment?
