### ISSUE TITLE
Import error in dev mode, not with wsgi virtualhost (virtualenv and vagrant)

### ISSUE THREAD

**Issue by quoidautre** [pallets/flask#3126]
---

### Expected Behavior
In my Flask project (Debian 8.10 VM, vagrant and virtualenvs), I use mapnik, and it's installed with apt-get (_with pip, there's a lot of errors_) : 
```shell
$ sudo apt-get install libmapnik2.2 mapnik-utils python-mapnik python-mapnik2    

$ dpkg -l | grep mapnik
ii  libmapnik2.2                         2.2.0+ds1-7+b2                     amd64        C++/Python toolkit for developing GIS applications (libraries)
ii  mapnik-utils                         2.2.0+ds1-7+b2                     amd64        C++/Python toolkit for developing GIS applications (utilities)
ii  python-mapnik                        2.2.0+ds1-7+b2                     amd64        C++/Python toolkit for developing GIS applications (Python)
ii  python-mapnik2                       2.2.0+ds1-7                        all          C++/Python toolkit for developing GIS applications (dummy)

```
I use an apache's virtualhost : 
```apache
<VirtualHost *:80>
        ServerName vm.my_app
        DocumentRoot /var/www/my_app/my_app
        WSGIDaemonProcess flask_my_app user=www-data group=www-data python-path=/var/www/my_app/my_app:/home/vagrant/.virtualenvs/my_app/lib/python2.7/site-packages display-name=%{GROUP}
        WSGIProcessGroup flask_my_app
        WSGIScriptAlias / /var/www/my_app/my_app/flask_my_app/flask_my_app.wsgi
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization on
        WSGIScriptReloading On

        Alias /site_media/ /var/www/my_app/my_app/site_media/
        Alias /media/ /var/www/my_app/my_app/media/
        Alias /static/ /var/www/my_app/my_app/static/
        AliasMatch /([/]*\.css) /var/www/my_app/my_app/static/css/$1

        <Directory /var/www/my_app/my_app>
            Order allow,deny
            Allow from all
            Require all granted
        </Directory>

        <Directory /var/www/my_app/my_app/flask_my_app>
            Order allow,deny
            Allow from all
            Require all granted
        </Directory>

</VirtualHost>
```
Ok, it's fine..., except that I must add some characters in the wsgi file when I change my code :(

And, so here the error : 
```
(No module named mapnik --> <type 'exceptions.ImportError'> => 
Traceback (most recent call last): 
File "/var/www/my_app/my_app/flask_my_app/views.py", line 202, in zonesmeteo t = importlib.import_module('cron_dept_treatments.%s' % dept_code) 
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module __import__(name) 
File "/var/www/my_app/my_app/cron_dept_treatments/20.py", line 17, in <module> import mapnik ImportError: No module named mapnik )
```
```pytb
(my_env)    
$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> flask.__path__
['/home/vagrant/.virtualenvs/my_app/local/lib/python2.7/site-packages/flask']
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mapnik
>>> quit()

(my_env)
$ deactivate

$ python
Python 2.7.9 (default, Sep 25 2018, 20:42:16)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
>>> mapnik.__path__
['/usr/lib/python2.7/dist-packages/mapnik']
>>>
```

### Environment

* Python version: 2.7
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

Thanks
F.

**Comment by ThiefMaster** [comment]
If you want to have access to globally-installed packages, make sure to create your virtualenv with `--system-site-packages`. Otherwise it has no access to anything installed outside the virtualenv.

**Comment by quoidautre** [comment]
Hi, 
Thanks, but can I modify the env ?, or,  I must remove it and regenerate it ?
