### ISSUE TITLE
RuntimeError: Attempted to use a closed Session. with flask

### ISSUE THREAD

**Issue by manuel3265** [pallets/flask#3141]
I'm trying to run a Tacotron-2 training in flask, get parameters in json format. but the following error arises when I execute the training:

```
ARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
Using TensorFlow backend.
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8891/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/local/lib/python3.6/dist-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
Using TensorFlow backend.
 * Debugger is active!
 * Debugger PIN: 303-138-053
Checkpoint path: logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt
Loading training data from: tacotron-files/servex-tacotron/training_data/train.txt
Using model: Tacotron
Hyperparameters:
  GL_on_GPU: True
  NN_init: True
  NN_scaler: 0.3
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  attention_win_size: 7
  batch_norm_position: after
  cbhg_conv_channels: 128
  cbhg_highway_units: 128
  cbhg_highwaynet_layers: 4
etc...
Tacotron Parameters       29.039 Million.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/losses/losses_impl.py:667: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
initialisation done /gpu:0
Initialized Tacotron model. Dimensions (? = dynamic shape): 
  Train mode:               False
  Eval mode:                True
  GTA mode:                 False
  Synthesis mode:           False
  Input:                    (?, ?)
  device:                   0
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out:              (?, ?, 512)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  linear out:               (?, ?, 1025)
  <stop_token> out:         (?, ?)
  Tacotron Parameters       29.039 Million.
Tacotron training set to a maximum of 200000 steps
holaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Loading checkpoint logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Exiting due to exception: '<' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/manuel_garcia02/Tacotron/tacotron/train.py", line 224, in train
    while not coord.should_stop() and step < args.tacotron_train_steps:
TypeError: '<' not supported between instances of 'int' and 'str'
186.179.100.228 - - [07/Apr/2019 02:52:15] "POST /tts/train HTTP/1.1" 200 -
Generated 15 test batches of size 32 in 0.891 sec
Generated 64 train batches of size 32 in 2.169 sec
Exception in thread background:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manuel_garcia02/Tacotron/tacotron/feeder.py", line 169, in _enqueue_next_train_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1075, in _run
    raise RuntimeError('Attempted to use a closed Session.')



```
Why can it be produced?
---

### Expected Behavior

I should start training normally

```python
Paste a minimal example that causes the problem.
```

```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version:

**Comment by davidism** [comment]
As the traceback shows, this is about tensorflow.
