### ISSUE TITLE
Running flask crashes Python on macOS 10.15

### ISSUE THREAD

**Issue by SamusAranX** [pallets/flask#3329]
**TL;DR:** Python crashes because of libcrypto shenanigans. Ignoring for the moment that I'm running a beta OS, is this a Flask problem or a Python problem? Flask worked beautifully before I upgraded to Python 3.7.4, even on 10.15.

### Expected Behavior
My application starts.

```
FLASK_ENV=development flask run --host=0.0.0.0
```

### Actual Behavior
Python crashes.

```
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Abort trap: 6
 * Debugger is active!
 * Debugger PIN: 244-572-746
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 783, in run_command
    threaded=with_threads, ssl_context=cert)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 326, in run_with_reloader
    ensure_echo_on()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 315, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (5, 'Input/output error')
```

Along with the traceback, I get a "Python quit unexpectedly." dialog from the OS itself:

```
Process:               Python [22680]
Path:                  /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.7.4 (3.7.4)
Code Type:             X86-64 (Native)
Parent Process:        bash [96512]
Responsible:           iTerm2 [96508]
User ID:               501

Date/Time:             2019-08-10 19:59:34.561 +0200
OS Version:            Mac OS X 10.15 (19A526h)
Report Version:        12
Bridge OS Version:     3.0 (14Y904)
Anonymous UUID:        01D731B3-953D-1E90-36A7-011EAA224529

Sleep/Wake UUID:       1BC6AE63-AA8F-4BEF-8027-28080B7A5B9E

Time Awake Since Boot: 16000 seconds
Time Since Wake:       6000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/usr/lib/libcrypto.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

### Environment

* Python version: 3.7.4
* Flask version: 1.1.1
* Werkzeug version: 0.15.5

**Comment by davidism** [comment]
Sounds like a Python problem. Note that Flask and Werkzeug tests pass on our Mac CI.

If you discover more information that suggests Flask should change, please let us know.
