### ISSUE TITLE
Accidental occurrence of environ[“REQUEST_METHOD”] key error on my production server, with flask+uwsgi service mode

### ISSUE THREAD

**Issue by skiwer** [pallets/flask#3357]
This error occasionally occurs on the production server, which using flask combine uwsgi and nginx. 

What I can see in the traceback below is the REQUEST_METHOD parameter is missing from the environment variable uwsgi passes to flask app.
```
Traceback (most recent call last):
  File "/home/projects/igor/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/projects/igor/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1977, in wsgi_app
    ctx = self.request_context(environ)
  File "/home/projects/igor/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1938, in request_context
    return RequestContext(self, environ)
  File "/home/projects/igor/virtualenv/lib/python2.7/site-packages/flask/ctx.py", line 242, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/home/projects/igor/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1765, in create_url_adapter
    server_name=self.config['SERVER_NAME'])
  File "/home/projects/igor/virtualenv/lib/python2.7/site-packages/werkzeug/routing.py", line 1524, in bind_to_environ
    environ["REQUEST_METHOD"],
KeyError: 'REQUEST_METHOD'
```

### Environment

* Python version:2.7.9
* Flask version:0.12

**Comment by davidism** [comment]
I can't reproduce this issue. uWSGI always provides this required key.

Note that Flask 0.12 is unsupported, you should upgrade to 1.1, although this shouldn't cause this issue.
