### ISSUE TITLE
flask db init error

### ISSUE THREAD

**Issue by danerlt** [pallets/flask#3385]
### Expected Behavior
I use `flask db init` execute error

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'

db = SQLAlchemy(app)
migrate = Migrate(app, db)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128))


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()

```

### Actual Behavior

```pytb
$ flask db init
Traceback (most recent call last):
  File "d:\data\conda\envs\sys_server\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\data\conda\envs\sys_server\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\data\conda\envs\sys_server\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "d:\data\conda\envs\sys_server\lib\site-packages\flask\cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "d:\data\conda\envs\sys_server\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "d:\data\conda\envs\sys_server\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\data\conda\envs\sys_server\lib\site-packages\click\core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "d:\data\conda\envs\sys_server\lib\site-packages\click\core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "d:\data\conda\envs\sys_server\lib\site-packages\flask\cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "d:\data\conda\envs\sys_server\lib\site-packages\flask\cli.py", line 523, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "C:\Users\tao\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "C:\Users\tao\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\tao\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Jinja2 2.10 (c:\users\tao\appdata\roaming\python\python37\site-packages), Requirement.parse('Jinja2>=2.10.1'),
 {'Flask'})

```

### Environment

* Python version: Python 3.7.3
* Flask version: 1.0.2
* Werkzeug version:0.16.0
* Flask-Migrate version: 2.5.2

**Comment by danerlt** [comment]
I use `flask run`, 'flask --help' will also appear,but I use `flask --version` is right,it print
```
Python 3.7.3
Flask 1.1.1
Werkzeug 0.16.0
```

**Comment by ThiefMaster** [comment]
looks like a problem on your side to me. try upgrading jinja2...

**Comment by danerlt** [comment]
@ThiefMaster I use `pip install --upgrade jinja2` command to upgrade jinja2,  still did not solve my problem.
```
Installing collected packages: MarkupSafe, Jinja2
Successfully installed Jinja2-2.10.3 MarkupSafe-1.1.1
```

**Comment by davidism** [comment]
I can't reproduce this issue. It sounds like a problem with your Python installation. The original error definitely means you need to upgrade to at least Jinja 2.10.1, but beyond that I can't say why it's failing. Does this happen with a fresh virtualenv?
