### ISSUE TITLE
Unable to extend FlaskClient with follow_redirects

### ISSUE THREAD

**Issue by MaicoTimmerman** [pallets/flask#3396]
I'm trying to add default headers to Flask's test client requests by overriding `FlaskClient.open`. When following redirects, the second request raises an error that an `EnvironBuilder` instance is being passed to `url_parse`.

### Expected Behavior

```python
from flask import Flask, redirect, url_for
from flask.testing import FlaskClient

app = Flask(__name__)

class CustomClient(FlaskClient):
    def open(self, *args, **kwargs):
        kwargs["headers"] = {"Extra-Key": "extra value"}
        return super().open(*args, **kwargs)

@app.route("/")
def home():
    return redirect(url_for("test"))

@app.route("/test")
def test():
    return "Hello, World!"

app.test_client_class = CustomClient
c = app.test_client()
rv = c.get("/", follow_redirects=True)
print(rv.data)
```

### Actual Behavior
```pytb
Traceback (most recent call last):
  File "/home/david/Projects/flask/example.py", line 21, in <module>
    rv = c.get("/", follow_redirects=True)
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/test.py", line 1029, in get
    return self.open(*args, **kw)
  File "/home/david/Projects/flask/example.py", line 9, in open
    return super().open(*args, **kwargs)
  File "/home/david/Projects/flask/src/flask/testing.py", line 222, in open
    return Client.open(
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/test.py", line 1016, in open
    environ, response = self.resolve_redirect(
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/test.py", line 948, in resolve_redirect
    return self.open(builder, as_tuple=True, buffered=buffered)
  File "/home/david/Projects/flask/example.py", line 9, in open
    return super().open(*args, **kwargs)
  File "/home/david/Projects/flask/src/flask/testing.py", line 215, in open
    builder = EnvironBuilder(self.application, *args, **kwargs)
  File "/home/david/Projects/flask/src/flask/testing.py", line 73, in __init__
    url = url_parse(path)
  File "/home/david/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/urls.py", line 457, in url_parse
    i = url.find(s(":"))
AttributeError: 'EnvironBuilder' object has no attribute 'find'
```
### Environment

* Python version: 3.6.9
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by liujunwe** [comment]
I repeated your code and didn't find your problem, but the test_client incoming header didn't show up in the Request Headrs after accessing the URL via the browser.
===========
**Environment** 

Python version: 3.7.3
Flask version: 1.1.1
Werkzeug version: 0.16.0

**Comment by MaicoTimmerman** [comment]
I'm not sure what you mean with accessing the URL via the browser. The script never serves the app, it directly calls the view functions. For completeness I've also ran the set-up in python 3.7.4, which resulted in exactly the same traceback (this trace is outside pycharm):

```pytb
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    rv = c.post("/", follow_redirects=True)
  File "/home/maico/dev/venv/lib/python3.7/site-packages/werkzeug/test.py", line 1039, in post
    return self.open(*args, **kw)
  File "test.py", line 14, in open
    return super().open(*args, **kwargs)
  File "/home/maico/dev/venv/lib/python3.7/site-packages/flask/testing.py", line 227, in open
    follow_redirects=follow_redirects,
  File "/home/maico/dev/venv/lib/python3.7/site-packages/werkzeug/test.py", line 1017, in open
    response, new_location, environ, buffered=buffered
  File "/home/maico/dev/venv/lib/python3.7/site-packages/werkzeug/test.py", line 948, in resolve_redirect
    return self.open(builder, as_tuple=True, buffered=buffered)
  File "test.py", line 14, in open
    return super().open(*args, **kwargs)
  File "/home/maico/dev/venv/lib/python3.7/site-packages/flask/testing.py", line 215, in open
    builder = EnvironBuilder(self.application, *args, **kwargs)
  File "/home/maico/dev/venv/lib/python3.7/site-packages/flask/testing.py", line 73, in __init__
    url = url_parse(path)
  File "/home/maico/dev/venv/lib/python3.7/site-packages/werkzeug/urls.py", line 457, in url_parse
    i = url.find(s(":"))
AttributeError: 'EnvironBuilder' object has no attribute 'find'
```

**Comment by liujunwe** [comment]
` from your trace, the type of the url is wrong. The url should not be the EnvironBuilder object. it should be str object , I'm not understand you project very well , may you need to debug the url type question`

**Comment by davidism** [comment]
The issue is that `FlaskClient.open` switches behavior based on if an `EnvironBuilder` is passed as the only argument. Because you're setting `headers` unconditionally, the "use existing builder" branch is skipped and it tries to create a new `EnvironBuilder`.
