### ISSUE TITLE
Getting KeyError: 'REQUEST_METHOD' sometimes

### ISSUE THREAD

**Issue by mdnahian** [pallets/flask#3422]
Getting this error sometimes when running flask with uwsgi and nginx:
Possibly similar to the issue here: [3357](https://github.com/pallets/flask/issues/3357)?

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_uwsgi_websocket/_gevent.py", line 59, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2453, in wsgi_app
    return response(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 700, in __call__
    app_iter, status, headers = self.get_wsgi_response(environ)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 689, in get_wsgi_response
    app_iter = self.get_app_iter(environ)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 662, in get_app_iter
    environ["REQUEST_METHOD"] == "HEAD"
KeyError: 'REQUEST_METHOD'
```

### Environment

* Python version: 3.6.8
* Flask version: 1.1.1
* Werkzeug version: 0.16.0
* uWSGI version: 2.0.18

**Comment by davidism** [comment]
I'm sorry, without more information I can't identify the issue or fix it.
