### ISSUE TITLE
Suggestion: Improve traceback for routes that return None

### ISSUE THREAD

**Issue by kg-2** [pallets/flask#3445]
### Expected Behavior

When a user creates a route that returns None flask raises

>  `TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.`

 The problem is that it doesn't include the route that actually caused the error. It's obviously not a huge deal, just a little tedious to go search through all of the routes.

full traceback:

```pytb
Traceback (most recent call last):
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/var/www/mysite.com/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

### Environment

* Python version: 3.6
* Flask version: 1.1.1
* Werkzeug version: 0.16

**Comment by kg-2** [comment]
side note:  this also seems to occur above the scope of the flask logger. Is there a typical flask convention for logging errors like this?

**Comment by safwan20** [comment]
can i know the filename where this code is located

**Comment by kg-2** [comment]
@safwan20 I think that was triggered from a view in
/blueprints/admin/views/users.py
