### ISSUE TITLE
TypeError: after_request() takes 0 positional arguments but 1 was given 

### ISSUE THREAD

**Issue by winfirm** [pallets/flask#3468]
before_request
addr：/
method：GET
---headers--start--
Host: localhost:5000
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/72.0.3626.119 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/a
png,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
---headers--end----
GET args：ImmutableMultiDict([])
POST args：ImmutableMultiDict([])
[2020-01-14 10:16:30,833] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch
_request
    return self.finalize_request(rv)
  File "c:\python37\lib\site-packages\flask\app.py", line 1969, in finalize_requ
est
    response = self.process_response(response)
  File "c:\python37\lib\site-packages\flask\app.py", line 2266, in process_respo
nse
    response = handler(response)
TypeError: after_request() takes 0 positional arguments but 1 was given
[2020-01-14 10:16:30,834] ERROR in app: Request finalizing failed with an error
while handling an error
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch
_request
    return self.finalize_request(rv)
  File "c:\python37\lib\site-packages\flask\app.py", line 1969, in finalize_requ
est
    response = self.process_response(response)
  File "c:\python37\lib\site-packages\flask\app.py", line 2266, in process_respo
nse
    response = handler(response)
TypeError: after_request() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\flask\app.py", line 1969, in finalize_requ
est
    response = self.process_response(response)
  File "c:\python37\lib\site-packages\flask\app.py", line 2266, in process_respo
nse
    response = handler(response)
TypeError: after_request() takes 0 positional arguments but 1 was given
127.0.0.1 - - [14/Jan/2020 10:16:30] "GET / HTTP/1.1" 500 -

**Comment by a289237642** [comment]
？？？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Winfirm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 上午10:22
收件人:&nbsp;"pallets/flask"<flask@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[pallets/flask] TypeError: after_request() takes 0 positional arguments but 1 was given  (#3468)




before_request
 addr：/
 method：GET
 ---headers--start--
 Host: localhost:5000
 Connection: keep-alive
 Upgrade-Insecure-Requests: 1
 User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML,
 like Gecko) Chrome/72.0.3626.119 Safari/537.36
 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/a
 png,/;q=0.8
 Accept-Encoding: gzip, deflate, br
 Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
 ---headers--end----
 GET args：ImmutableMultiDict([])
 POST args：ImmutableMultiDict([])
 [2020-01-14 10:16:30,833] ERROR in app: Exception on / [GET]
 Traceback (most recent call last):
 File "c:\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
 response = self.full_dispatch_request()
 File "c:\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch
 _request
 return self.finalize_request(rv)
 File "c:\python37\lib\site-packages\flask\app.py", line 1969, in finalize_requ
 est
 response = self.process_response(response)
 File "c:\python37\lib\site-packages\flask\app.py", line 2266, in process_respo
 nse
 response = handler(response)
 TypeError: after_request() takes 0 positional arguments but 1 was given
 [2020-01-14 10:16:30,834] ERROR in app: Request finalizing failed with an error
 while handling an error
 Traceback (most recent call last):
 File "c:\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
 response = self.full_dispatch_request()
 File "c:\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch
 _request
 return self.finalize_request(rv)
 File "c:\python37\lib\site-packages\flask\app.py", line 1969, in finalize_requ
 est
 response = self.process_response(response)
 File "c:\python37\lib\site-packages\flask\app.py", line 2266, in process_respo
 nse
 response = handler(response)
 TypeError: after_request() takes 0 positional arguments but 1 was given
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "c:\python37\lib\site-packages\flask\app.py", line 1969, in finalize_requ
 est
 response = self.process_response(response)
 File "c:\python37\lib\site-packages\flask\app.py", line 2266, in process_respo
 nse
 response = handler(response)
 TypeError: after_request() takes 0 positional arguments but 1 was given
 127.0.0.1 - - [14/Jan/2020 10:16:30] "GET / HTTP/1.1" 500 -

**Comment by davidism** [comment]
After request functions take the response as an argument.

**Comment by realitypastor** [comment]
* Detected change in 'C:\\Users\\EMERIT\\Desktop\\net\\app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 815-788-892
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [03/Aug/2020 01:25:09] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\EMERIT\Desktop\net\app.py", line 20, in index
    posts = get_posts('post')
TypeError: get_posts() takes 0 positional arguments but 1 was given

**Comment by realitypastor** [comment]
* Detected change in 'C:\\Users\\EMERIT\\Desktop\\net\\app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [03/Aug/2020 01:25:09] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\EMERIT\Desktop\n88-892et\myenv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\EMERIT\Desktop\net\myenv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\EMERIT\Desktop\net\app.py", line 20, in index
    posts = get_posts('post')
TypeError: get_posts() takes 0 positional arguments but 1 was given
