### ISSUE TITLE
Greedy version requirement for werkzeug breaking fresh installs

### ISSUE THREAD

**Issue by JacThomp** [pallets/flask#3481]
Any fresh installs/updates to flask as of the last few hours crash with an import error
> ImportError: cannot import name 'url_encode' from 'werkzeug' (/Users/me/env/lib/python3.7/site-packages/werkzeug/__init__.py) 

due to a major version change in werkzeug (from 0.16.1 to 1.0.0), as per https://github.com/pallets/werkzeug/issues/1714

**Comment by ThiefMaster** [comment]
please show a full traceback.

**Comment by JacThomp** [comment]
Traceback (most recent call last):
  File "/Users/me/env/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/Users/me/env/lib/python3.7/site-packages/airflow/bin/cli.py", line 70, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "/Users/me/env/lib/python3.7/site-packages/airflow/www/app.py", line 26, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/Users/me/env/lib/python3.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/Users/me/env/lib/python3.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/Users/me/env/lib/python3.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/Users/me/env/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/Users/me/env/lib/python3.7/site-packages/werkzeug/__init__.py)

**Comment by david-reclaimhealth** [comment]
Related stack trace for this same issue:
`cannot import name 'cached_property': ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 139, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/manage_consumer.py", line 35, in <module>
    from reclaim_consumer import create_app, DB
  File "/var/task/reclaim_consumer/__init__.py", line 13, in <module>
    from .api import API
  File "/var/task/reclaim_consumer/api.py", line 3, in <module>
    from flask_restplus import Api
  File "/var/task/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/var/task/flask_restplus/fields.py", line 17, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'
`

**Comment by ThiefMaster** [comment]
Those are all flask extensions, not flask itself. Werkzeug 0.16 deprecated those top-level imports almost 5M ago, so the maintainers of those extensions had plenty of time to update them to use the correct imports...

**Comment by tjohnson4** [comment]
Is there a work around here? This has broken our ability to build our app which uses connexion. Explicitly setting 0.16.1 did not resolve this. 

`Traceback (most recent call last):
  File "smid_service/app.py", line 1, in <module>
    from smid_service import create_app
  File "/app/smid_service/__init__.py", line 1, in <module>
    import connexion
  File "/usr/local/lib/python3.7/site-packages/connexion/__init__.py", line 3, in <module>
    import werkzeug.exceptions as exceptions  # NOQA
  File "/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py", line 220, in <module>
    from .serving import run_simple
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 48, in <module>
    from ._internal import _log
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_internal.py", line 11, in <module>
    import inspect
  File "/usr/local/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/usr/local/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "/app/smid_service/token.py", line 1, in <module>
    from sqlalchemy import create_engine
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 16, in <module>
    from .compat import binary_types
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 270, in <module>
    from inspect import formatannotation
ImportError: cannot import name 'formatannotation' from 'inspect' (/usr/local/lib/python3.7/inspect.py)`

**Comment by davidism** [comment]
That error appears to be from SQLAlchemy.

**Comment by tjohnson4** [comment]
> @tjohnson4 That error appears to be from SQLAlchemy.
Correct traceback above

**Comment by ThiefMaster** [comment]
`connexion` is also not part of flask; so it's a problem on their side.

**Comment by tjohnson4** [comment]
> `connexion` is also not part of flask; so it's a problem on their side.
So they are to blame for this exception? 
`ImportError: cannot import name 'url_encode' from 'werkzeug' (/Users/me/env/lib/python3.7/site-packages/werkzeug/__init__.py)`

**Comment by ThiefMaster** [comment]
Yes, look at the traceback!

```
2020-02-06 22:32:49 File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 9, in <module>
                                                                 ^^^^^^^^^
2020-02-06 22:32:49 from werkzeug import FileStorage
```

**Comment by julenpardo** [comment]
Setting `werkzeug==0.16.1` in your requirements file fixes it. The issue is with the 1.0.0 version released yesterday https://pypi.org/project/Werkzeug/1.0.0/

**Comment by EwetoyeIbrahim** [comment]
I have learned in a hard way...
Thanks to @julenpardo, downgrading to `werkzeug==0.16.1` resolves the issue, at least, for now.
Note that just installing Flask picks up the latest werkzeug, thus, `werkzeug==0.16.1` must be explicitly stated.
