### ISSUE TITLE
Flask Quickstart on master branch; minimal example fails with NameError

### ISSUE THREAD

**Issue by pgkrit** [pallets/flask#3527]
I pulled the latest version of flask Flask from the master branch, commit 64ba43411fbfb2e435455b0df2453d7809b7c5a8.

The Quickstart minimal example on the dev version of Flask does not run as intended.  Previous versions of the Quickstart example would display a simple "Hello world" message, but the addition of an undefined "name" variable causes the example to fail with a NameError.

It seems that the intention was to illustrate Werkzeug's HTML escaping functionality early-on, which makes sense, but the example needs to be restructured or augmented so that it still runs.

I'm aware that this is a development version of Flask, so my apologies if this (possibly known?) issue should be reported elsewhere or can be ignored.  Thanks.

### Expected Behavior

The Quickstart doc says that running the example should display a "Hello world" message when navigating to http://127.0.0.1:5000/.

```python
from flask import Flask
from markupsafe import escape

app = Flask(__name__)

@app.route("/")
def hello_world():
    return f"<p>Hello, {escape(name)}!</p>"
```

### Actual Behavior
The browser displays an Internal Server Error response from Flask due to a NameError.

```pytb
Traceback (most recent call last):
  File "/home/pkritikos/work/flask_playground/venv/lib/python3.6/site-packages/flask/app.py", line 2430, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkritikos/work/flask_playground/venv/lib/python3.6/site-packages/flask/app.py", line 1945, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkritikos/work/flask_playground/venv/lib/python3.6/site-packages/flask/app.py", line 1814, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkritikos/work/flask_playground/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pkritikos/work/flask_playground/venv/lib/python3.6/site-packages/flask/app.py", line 1943, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkritikos/work/flask_playground/venv/lib/python3.6/site-packages/flask/app.py", line 1929, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkritikos/work/flask_playground/tutorial/__init__.py", line 8, in hello_world
    return f"<p>Hello, {escape(name)}!</p>"
```

### Environment

* Python version: Python 3.6.9
* Flask version: Flask 1.2.0.dev0
* Werkzeug version: Werkzeug 1.0.0

**Comment by ThiefMaster** [comment]
Indeed, that example is using a `name` that's not defined anywhere...

**Comment by pgkrit** [comment]
The "Variable Rules" section of the Quickstart would be a reasonable place to introduce the escaping functionality.  I can create a PR with a proposed change.

**Comment by pgkrit** [comment]
Created https://github.com/pallets/flask/pull/3529.

Adding the note about escaping user input in the Variable Rules section makes logical sense, but it might not catch the reader's attention when placed below the table of conversion types.  I'd welcome others' feedback.  Thanks.
