### ISSUE TITLE
Errorhandler not work for ValidationError from marshmallow

### ISSUE THREAD

**Issue by Cheban1996** [pallets/flask#3528]
### Expected Behavior
When happens exeption ValidationError i waiting that be handled function handle_exception

### Actual Behavior
```pytb
  File "/usr/lib/python3.7/site-packages/marshmallow/schema.py", line 892, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'active': ['Not a valid boolean.']}
```

### Environment

* Python version: 3.8
* Flask version: 1.1.1
* Werkzeug version: 0.16.1
* Marshmallow: 3.5.0

```
@app.errorhandler(marshmallow.exceptions.ValidationError)
def handle_exception(e):
    return {'message': e.normalized_messages()}, 400
```

**Comment by davidism** [comment]
Please provide a minimal but complete example reproducing the issue.

**Comment by Cheban1996** [comment]
@davidism 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/cb_api/api_gateway/services/jwt_service.py", line 101, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/cb_api/api_gateway/api/admin_resources/exchange.py", line 39, in put
    marshmallow_result = ExchangeSchema().load(kwargs, partial=True)
  File "/usr/lib/python3.7/site-packages/marshmallow/schema.py", line 714, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/usr/lib/python3.7/site-packages/marshmallow/schema.py", line 892, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'active': ['Not a valid boolean.']}

**Comment by davidism** [comment]
That's a traceback, and while it's useful, I need a minimal complete example demonstrating the issue.

**Comment by Cheban1996** [comment]
```
@app.errorhandler(marshmallow.exceptions.ValidationError)
def handle_exception(e):
    return {'message': e.normalized_messages()}, 400

class MySchema(ma.Schema):
    class Meta:
        unknown = EXCLUDE
    name = ma.String()
    age = ma.Integer()

@app.route("/")
def put():
        data = MySchema().load(request.json)
        ....
        return {'data': data}
```
I hope this help you.
