### ISSUE TITLE
Tensorflow and Flask reloader not playing nicely

### ISSUE THREAD

**Issue by mulka** [pallets/flask#3549]
### Expected Behavior

When running flask via `flask run --reload`, importing TensorFlow should not cause an error. Leaving out the --reload flag does work.

```python
# Paste a minimal example that causes the problem.
import tensorflow
from flask import Flask
app = Flask(__name__)
```

### Actual Behavior
This error occurs:

```pytb
Traceback (most recent call last):
  File "venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/flask/cli.py", line 860, in run_command
    extra_files=extra_files,
  File "venv/lib/python3.7/site-packages/werkzeug/serving.py", line 1050, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "venv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 337, in run_with_reloader
    reloader.run()
  File "venv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 202, in run
    for filename in chain(_iter_module_files(), self.extra_files):
  File "venv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 24, in _iter_module_files
    filename = getattr(module, "__file__", None)
  File "venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Users/mulka/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.keras'

```

### Environment

* Python version: 3.7.6
* Flask version: 1.1.1
* Werkzeug version: 1.0.0
* TensorFlow version: 2.1.0

**Comment by davidism** [comment]
It's not clear that Werkzeug's reloader is doing anything in particular that would affect this. This is something tensorflow will have to address.

**Comment by mulka** [comment]
@davidism Unfortunately I wasn't able to reproduce this with just Werkzeug. I could only reproduce it with the flask run command. For example, this seems to work ok:

```
import tensorflow
from werkzeug.wrappers import Request, Response
from werkzeug.serving import run_simple

@Request.application
def application(request):
    return Response('Hello, World!')


run_simple('localhost', 4000, application, use_reloader=True)
```

**Comment by davidism** [comment]
Try turning off lazy loading: `flask run --eager-loading`. That's the only thing Flask really adds, it tries to load the app in a thread to survive syntax errors. If that's messing with Tensorflow, I don't think there's much we can do.

**Comment by mulka** [comment]
Thank you. It looks like adding the --eager-loading flag did fix it.
