### ISSUE TITLE
Error when apply tojson or flask.json.dumps on dict with None as key

### ISSUE THREAD

**Issue by XD-DENG** [pallets/flask#3599]
#### 1. Example Application

- `app.py`

```python
from flask import Flask, render_template

app = Flask(__name__)


@app.route("/")
def hello_world():
    data = {"X": 1,
            "Y": True,
            None: "abc"}

    return render_template("index.html", data=data)


if __name__ == "__main__":
    app.run(debug=True)

```

-  `templates/index.html`

```html
<html>

<script>
 const a = {{ data|tojson }};
</script>

<p>Hi</p>

</html>
```

#### 2. Example Single-Line Code

The same issue will be triggered if you run code below

```python
flask.json.dumps({None: 1, "X": 2})
```

### Actual Behavior

```pytb
Traceback (most recent call last):
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/XD/Desktop/flask_temp/app.py", line 11, in hello_world
    return render_template("index.html", data=data)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/XD/Desktop/flask_temp/templates/index.html", line 4, in top-level template code
    const a = {{ data|tojson }};
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/json/__init__.py", line 376, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/json/__init__.py", line 290, in htmlsafe_dumps
    dumps(obj, **kwargs)
  File "/Users/XD/Library/Python/3.7/lib/python/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

### Environment

* OS: Darwin 19.3.0 Darwin Kernel Version 19.3.0
* Python: 3.7.3 (this issue is inapplicable for Python 2.7)
* Flask: 1.1.2
* Werkzeug: 1.0.1

### Root Cause

Python 3 would fail to sort keys when it processes `json.dumps(dict, sort_keys=True)` if there are multiple keys in the dict and one key is `None`. E.g., `json.dumps({None: 1, "X": 2}, sort_keys=True)`

(`None` is legal as a key in Python dict.)

Normally this is not an issue because `json.dumps()`'s default value for `sort_keys` is `False`. However, in Flask, default value for `JSON_SORT_KEYS` is alwasy `True` for caching ([reference](https://flask.palletsprojects.com/en/1.1.x/config/#JSON_SORT_KEYS)).

**Comment by davidism** [comment]
You need to fix your data, JSON should only have string keys. I don't think this is something Flask should allow.

**Comment by davidism** [comment]
To clarify, this is not just an issue with `None`, it's an issue with any non-string as keys. Python will be nice and coerce the keys to strings (including `None` to `"null"`), but apparently that step happens after sorting. The order of those steps should perhaps be a bug report to Python.

**Comment by XD-DENG** [comment]
Hi @davidism . Thanks for the prompt response.

I'm more than fine with your opinion, and understand it may not be desirable for framework like Flask to cover too many logics for 'edge cases'.

If it's true like you said, all non-string as keys in dict may cause issue in this scenario, it may be nice for Flask to do simple check and explicitly reject non-compliant dict for `flask.json.dumps/dump`. Otherwise users get too generic error message like the one above and need more time to investigate what's happening.

Let me know your thoughts?

**Comment by davidism** [comment]
Libraries like Marshmallow are a better choice to validate and serialize Python data.
