### ISSUE TITLE
Flask 1.1.x custom error handler fills up the console with tons of exceptions

### ISSUE THREAD

**Issue by NaturalBornCamper** [pallets/flask#3617]
### Expected Behavior
Custom handler exception should execute and leave the console alone

```python
# Instead of always getting "Internal server error" default response, this permits to use our
# own error handlers
app.config['PROPAGATE_EXCEPTIONS'] = True

formatter = logging.Formatter("")
handler = RotatingFileHandler('errors.log', maxBytes=10000, backupCount=1)
handler.setFormatter(formatter) # Tried not setting a formatter as well, same result
handler.setLevel(logging.ERROR)
logging.getLogger('warnings').addHandler(handler)
logging.getLogger().addHandler(handler)

# MySQL connection issues
@app.errorhandler(OperationalError)
def handle_database_error(err):
    # The line below doesn't output anything in the console
    logging.getLogger().error(err)

    # The line below outputs tons of lines of stack trace in the console
    logging.getLogger('errors').error(err)
```

### Actual Behavior
In the code above, if using the built-in handler logging.getLogger().error(err) It will output only 127.0.0.1 - - [14/May/2020 15:56:22] "GET /platforms/8 HTTP/1.1" 500 - which is the desired result when using a bad password for the DB.

However, if using the custom handler logging.getLogger('errors').error(err), the console gets filled with garbage and a long stack trace of exceptions causing other exceptions, with 3 messages like these:

"During handling of the above exception, another exception occurred"
"The above exception was the direct cause of the following exception"

Been on this for almost 2 weeks now, no answer on StackOverflow so I'm starting to think this is a bug, no matter what I do, I can't find what's causing this.

Furthermore, the stack trace is almost always files in site-packages, library files that are outside of my own files scope.

```pytb
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 140, in _do_get
    self._dec_overflow()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 137, in _do_get
    return self._create_connection()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user 'app'@'%' to database 'app_deva'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return self.handle_error(e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\DEV\api\resources\platform.py", line 19, in get
    watch_item = WatchItemModel.find_by_id(watch_item_id)
  File "E:\DEV\api\core\model.py", line 34, in find_by_id
    return cls.query.filter_by(**{cls.__primary_key__: id_}).first()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3375, in first
    ret = list(self[0:1])
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3149, in __getitem__
    return list(res)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3518, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3496, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\session.py", line 1141, in connection
    execution_options=execution_options,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2311, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 140, in _do_get
    self._dec_overflow()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 137, in _do_get
    return self._create_connection()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1044, "Access denied for user 'app'@'%' to database 'app_deva'")
(Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\logging\handlers.py", line 1020, in emit
    smtp.login(self.username, self.password)
  File "c:\python37\lib\smtplib.py", line 697, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
Call stack:
Traceback (most recent call last):
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 140, in _do_get
    self._dec_overflow()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 137, in _do_get
    return self._create_connection()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user 'app'@'%' to database 'app_deva'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\DEV\api\resources\platform.py", line 19, in get
    watch_item = WatchItemModel.find_by_id(watch_item_id)
  File "E:\DEV\api\core\model.py", line 34, in find_by_id
    return cls.query.filter_by(**{cls.__primary_key__: id_}).first()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3375, in first
    ret = list(self[0:1])
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3149, in __getitem__
    return list(res)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3518, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\query.py", line 3496, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\session.py", line 1141, in connection
    execution_options=execution_options,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\orm\session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2311, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 140, in _do_get
    self._dec_overflow()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\impl.py", line 137, in _do_get
    return self._create_connection()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1044, "Access denied for user 'app'@'%' to database 'app_deva'")
(Background on this error at: http://sqlalche.me/e/e3q8)

  File "c:\python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "c:\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\werkzeug\serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "c:\python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\werkzeug\serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\werkzeug\serving.py", line 314, in execute
    for data in application_iter:
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\werkzeug\debug\__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\Marco\.virtualenvs\api-kHflOUBu\lib\site-packages\flask\app.py", line 1822, in handle_user_exception
    return handler(e)
  File "E:\DEV\api\components\error_handler.py", line 33, in handle_database_error
    return ErrorHandler.error(errors.DATABASE_ACCESS, err, traceback.format_exc())
  File "E:\DEV\api\components\error_handler.py", line 86, in error
    logging.getLogger('errors').error(err, extra=ErrorHandler.get_details())
Message: OperationalError('(pymysql.err.OperationalError) (1044, "Access denied for user \'app\'@\'%\' to database \'app_deva\'")')
Arguments: ()
127.0.0.1 - - [18/May/2020 20:26:50] "GET /platforms/8 HTTP/1.1" 500 -
```

### Environment

* Python version: 3.7.7
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by NaturalBornCamper** [comment]
Please delete!!

I cannot believe I have been struggling 2 weeks to find the issue, then immediately after posting I found what was causing this, not a bug, entirely my fault! Feel stupid now :/
