### ISSUE TITLE
Error on Flask run command

### ISSUE THREAD

**Issue by eugenekgn** [pallets/flask#3635]
Getting the following error when running **flask run** command

```
(venev) C:\Users\eugen\Documents\development\flask_api>flask run

 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "C:\Users\eugen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\eugen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\eugen\Documents\development\flask_api\venev\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "c:\users\eugen\documents\development\flask_api\venev\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
ValueError: source code string cannot contain null bytes

```

**Comment by davidism** [comment]
This appears to be an issue with how you installed Flask, not with Flask itself. Try creating a new virtualenv, update pip, and reinstall Flask. Unfortunately, it's not something we can help with here.
