### ISSUE TITLE
send_file returns part of a file to a client when running with gevent worker on python 2.7.x

### ISSUE THREAD

**Issue by bimhud** [pallets/flask#3655]
```python
   send_file returns part of a file to a client when running with gevent worker.  This is happening with python 2.7.17. Working well with Python 3. When removing gevent working and running with gthreads, there is no issue at all with the send_file.  See details below. 
   Flask stills return 200 regardless the error.

`            return send_file(output_file,
                             mimetype=mimetype,
                             attachment_filename=os.path.basename(output_file),
                             as_attachment=True)
`
```

### Actual Behavior
send_file() is returning a part of actual file content and causing networking error. 
In somehow, content of the file is cut off

```pytb
Server log error recorded 


[2020-06-17 13:37:27 +0000] [256] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 112, in handle_request
    resp.write_file(respiter)
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 403, in write_file
    if not self.sendfile(respiter):
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 393, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 38, in _gevent_sendfile
    return o_sendfile(fdout, fdin, offset, nbytes)
  File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 66, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 0] Success
```

### Environment

* Python version: 2.7.17

* Gunicorn version: 19.9.0
* Geven version: 20.6.2
* Flask version: 1.1.1

* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
Due to the way `send_file` and HTTP works, if there is an error after the request starts, it still appears to be a 200 even though it fails later, because the status has to be sent at the start of the response, it can't be changed later. Unfortunately there's not enough information here to debug your issue, but I'd guess it's not specific to Flask, since Gevent does in fact work for serving files. Also note that Python 2.7 will no longer be supported in the next release, although it's also not clear if that's related to the issue.

**Comment by bimhud** [comment]
@davidism, I replace the send_file with a direct return of the content of the output_file, it's working fine in this way. Based on the traceback error, I still believe there is something from the send_file function that can be looked at.

**Comment by davidism** [comment]
Everything in the traceback is from Gunicorn, not Flask.
