### ISSUE TITLE
Discrepancy in logging output between IDLE and Terminal for Flask 0.12.x

### ISSUE THREAD

**Issue by undefined-func** [pallets/flask#3753]
```
import flask

app = flask.Flask(__name__)

@app.route("/")
def about():
    return hello #Intentional error

if __name__ == "__main__":
    app.run(debug=True)
```
The code above exposes the Werkzeug development server debugger. The debugger PIN is not printed to stdout in IDLE Shell, which prevents the developer from executing arbitrary code through the browser.
### Expected Behavior

```bash
bash output:
$ python3 test.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 334-139-720
127.0.0.1 - - [05/Sep/2020 17:51:30] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eExamSystem/Documents/app.py", line 7, in about
    return hello
NameError: name 'hello' is not defined
127.0.0.1 - - [05/Sep/2020 17:51:30] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2020 17:51:30] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2020 17:51:30] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2020 17:51:30] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2020 17:51:30] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
 * To enable the debugger you need to enter the security pin:
 * Debugger pin code: 334-139-720
127.0.0.1 - - [05/Sep/2020 17:51:33] "GET /?__debugger__=yes&cmd=printpin&s=3wa28jD2K14deHoUckzK HTTP/1.1" 200 -
```

### Actual Behavior

```pytb
================= RESTART: /Users/eExamSystem/Documents/app.py =================
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
```

### Environment

* Python version: 3.6.4
* Flask version: 0.12.2
* Werkzeug version: 0.15.4

**Comment by ThiefMaster** [comment]
Sounds more like a problem in IDLE to me....

**Comment by davidism** [comment]
Sorry, Flask 0.12 and Werkzeug 0.15 is no longer supported. As ThiefMaster says, it's not clear that this is an issue with Flask.
