### ISSUE TITLE
Error when trying to start flask app from command line

### ISSUE THREAD

**Issue by P-T-I** [pallets/flask#3815]
### Expected Behavior
Running a flask app from terminal command line

```python
flask run
```

### Actual Behavior
App doesn't start but instantly throws an error

```pytb
Traceback (most recent call last):
  File "/home/paul/PycharmProjects/APT/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/flask/cli.py", line 523, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Flask-Login 0.5.0 (/home/paul/PycharmProjects/APT/venv/lib/python3.6/site-packages), Requirement.parse('Flask-Login<0.5,>=0.3'))
```

In line with the error traceback; downgrading to Flask-Login 0.4.1 solves the issue

### Environment

* Python version: 3.6.9
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
You have another dependency installed that requires a lower version of Flask-Login than what you've installed. This isn't Flask, this is setuptools/pkg_resources telling you this.

**Comment by P-T-I** [comment]
@davidism You're right! Thanks!
