### ISSUE TITLE
Cannot run flask on python 3.9

### ISSUE THREAD

**Issue by tokra** [pallets/flask#3906]
I followed basic example in root of flask repo but after: flask run i got this isssue:
```log
* Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 376, in load_app
    app = locate_app(self, import_name, None,
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/tokra/Documents/Code/ghe/flash-test/app.py", line 4, in <module>
    app = Flask(__name__)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 558, in __init__
    self.add_url_rule(
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1216, in add_url_rule
    self.url_map.add(rule)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 1563, in add
    rule.bind(self)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 710, in bind
    self.compile()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 766, in compile
    self._build = self._compile_builder(False)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 1129, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 1120, in compile
    co = types.CodeType(*code_args)
TypeError: code() takes at least 14 arguments (13 given)
```

Here is my python version:
```
python3 -V
Python 3.9.1
```

I'm running it on:  `macOS Catalina 10.15.7`

Can you help pls ?

**Comment by davidism** [comment]
Upgrade Werkzeug: `pip install -U werkzeug`
