### ISSUE TITLE
Application dispatching pattern raises exception with debug configuration

### ISSUE THREAD

**Issue by JuanGarcia345** [pallets/flask#3911]
Hi,

I'm having trouble to use the [application dispatching pattern](https://flask.palletsprojects.com/en/1.1.x/patterns/appdispatch/#dispatch-by-path) and deploy it on a `gunicorn` server. The issue there is that when request size is (too?) large then the server resets the connexion (see [issue at gunicorn repo](https://github.com/benoitc/gunicorn/issues/2474)).

While trying to understand what problem is, I set the `flask` application in debug mode and unfortunately the pattern stops working as an exception is thrown.

The code for the server is:

```python
import flask
import threading
import werkzeug

def make_secondary_app():

    blueprint = flask.Blueprint("secondary", __name__)

    app = flask.Flask("secondary")

    @blueprint.route("/", methods=["POST"])
    def entry_secondary():
        request_data = flask.request.get_data().decode()
        return str(len(request_data))

    app.register_blueprint(blueprint)

    return app


class PathDispatcher(object):
    def __init__(self):

        self.lock = threading.Lock()
        self.default_app = flask.Flask("default_server")
        self.json_app = make_secondary_app()

        self.json_app.config.from_mapping({"DEBUG": True})  # Server works without this

    def get_application(self, prefix):

        with self.lock:

            if prefix == "secondary":
                return self.json_app

            return self.default_app

    def __call__(self, environ, start_response):

        # Get application associated to prefix
        app = self.get_application(werkzeug.wsgi.peek_path_info(environ))

        # Remove prefix from path
        werkzeug.wsgi.pop_path_info(environ)

        # Call real (secondary) application
        return app(environ, start_response)


def make_main_app():
    return PathDispatcher()


if __name__ == "__main__":

    werkzeug.run_simple(
        "127.0.0.1", 5000, make_main_app(), use_debugger=True, use_reloader=True
    )
```
### Expected Behavior

The request:
```python
import requests
rep = requests.post("http://127.0.0.1:5000/secondary", data={"a": b" "})
print(rep.content)
```
should print _3_

### Actual Behavior

On server side:
```python
Traceback (most recent call last):
  File "/home/garcia/Code/MC3/abyss-mca-ia/sandbox/bug_urllib3/server.py", line 51, in __call__
    return app(environ, start_response)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/garcia/.pyenv/versions/3.9.1/envs/bug-gunicorn/lib/python3.9/site-packages/flask/app.py", line 1912, in raise_routing_exception
    raise FormDataRoutingRedirect(request)
flask.debughelpers.FormDataRoutingRedirect: b'A request was sent to this URL (http://127.0.0.1:5000/secondary/) but a redirect was issued automatically by the routing system to "http://127.0.0.1:5000/secondary/".  Make sure to directly send your POST-request to this URL since we can\'t make browsers or HTTP clients redirect with form data reliably or without user interaction.\n\nNote: this exception is only raised in debug mode'
```

and the client receives the same message as a HTML doc.

### Environment

- Flask 1.1.2
- requests 2.25.0
- urllib3 1.26.2
- Werkzeug 1.0.1
- Python 3.9.1

Thanks for your help!

**Comment by JuanGarcia345** [comment]
@davidism Thanks a lot for your quick reply! This in fact a minimal exemple, please correct me if I'm wrong but the `DispatcherMiddleware` only makes _static_ dispatching. The intended application is to dynamically create a Flask app according to the path on the URL, that being said it seems to work on release mode but adding:

```python
self.json_app.config.from_mapping({"DEBUG": True}) 
```

raises an exception.

If you want I can rewrite the example to stick even more to the code given in the Flask user's guide but can you please explain why there is an issue with my interpretation (use) of the pattern? Is there another way to dynamically create Flask apps as a function of the URL?
