### ISSUE TITLE
Just test your code and how solve this error

### ISSUE THREAD

**Issue by okcrinum** [pallets/flask#3949]
sqlite3.OperationalError
sqlite3.OperationalError: no such table: post

Traceback (most recent call last)
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 2464, in __call__
 
Open an interactive python shell in this frame    ​def __call__(self, environ, start_response)
        """The WSGI server calls the Flask application object as the
        WSGI application. This calls :meth:`wsgi_app` which can be
        wrapped to applying middleware."""
        return self.wsgi_app(environ, start_response)
 
    def __repr__(self):
        return "<%s %r>" % (self.__class__.__name__, self.name)
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\user\flaskr\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\user\flaskr\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\user\flaskr\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\Python\WorkSpace\flaskr\flaskr\blog.py", line 20, in index
posts = db.execute(
sqlite3.OperationalError: no such table: post

**Comment by okcrinum** [comment]
I just run  the init-db command: and its work now, thank you
