### ISSUE TITLE
2.0.0: build requires ContextVar module

### ISSUE THREAD

**Issue by kloczek** [pallets/flask#4015]
Simple I cannot find it.
```console
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 689, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/usr/lib/python3.8/site-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/lib/python3.8/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.8/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/lib/python3.8/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/lib/python3.8/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python3.8/site-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/Flask-2.0.0/src/flask/__init__.py", line 7, in <module>
    from .app import Flask
  File "/home/tkloczko/rpmbuild/BUILD/Flask-2.0.0/src/flask/app.py", line 19, in <module>
    from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/usr/lib/python3.8/site-packages/werkzeug/local.py)
```

**Comment by ThiefMaster** [comment]
You need werkzeug 2 as well...
