### ISSUE TITLE
Flask 2.0 Bug

### ISSUE THREAD

**Issue by uzeyiroztemur** [pallets/flask#4023]
-> env/bin/python migrate.py db upgrade
Traceback (most recent call last):
  File "migrate.py", line 1, in <module>
    from flask_script import Manager
  File "********/env/lib/python3.6/site-packages/flask_script/__init__.py", line 15, in <module>
    from flask._compat import text_type
ModuleNotFoundError: No module named 'flask._compat'

**Comment by ThiefMaster** [comment]
not a flask bug but a flask-script issue. considering that it's not longer actively maintained you may want to migrate to flask's click-based cli.
