### ISSUE TITLE
On flask run "AttributeError: module 'colorama' has no attribute 'AnsiToWin32'"

### ISSUE THREAD

**Issue by kjaymiller** [pallets/flask#4046]
Instead starting and beginning to listen for requests on `flask run`, I recieve the error below

```
* Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/Users/kjaymiller/.pyenv/versions/edu-flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/flask/cli.py", line 849, in run_command
    run_simple(
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/werkzeug/serving.py", line 990, in run_simple
    log_startup(s)
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/werkzeug/serving.py", line 935, in log_startup
    _log(
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/werkzeug/_internal.py", line 223, in _log
    _logger.addHandler(_ColorStreamHandler())
  File "/Users/kjaymiller/.pyenv/versions/3.9.1/lib/python3.9/site-packages/werkzeug/_internal.py", line 201, in __init__
    stream = colorama.AnsiToWin32(sys.stderr)
AttributeError: module 'colorama' has no attribute 'AnsiToWin32'
```

```
import os

from flask import Flask

# Create Flask App
app = Flask(__name__)
app.secret_key = os.urandom(16)

if __name__ == "__main__":
    app.run(debug=True)
```

Environment:

- Python version: 3.9.1
- Flask version: 2.0.0
Using Pyenv, pip-tools, and a virtualenv

**Comment by davidism** [comment]
I can't reproduce this. The example given works as expected. Since you're not on Windows, you shouldn't have colorama installed (it does nothing). Maybe it's coming from another dependency. But it still has the class on Linux, so I'm not sure what's causing the error in your case.

**Comment by kjaymiller** [comment]
Issue is apparently IDE related as in terminal alone it seems to function. Closing this.
