### ISSUE TITLE
Python 3.10 test failures: DeprecationWarning: There is no current event loop (might be asgiref)

### ISSUE THREAD

**Issue by mgorny** [pallets/flask#4077]
The following tests fail when running the test suite under Python 3.10.0b1:

```
FAILED tests/test_async.py::test_async_route[/] - assert b'GET' in b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Intern...
FAILED tests/test_async.py::test_async_route[/home] - assert b'GET' in b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 In...
FAILED tests/test_async.py::test_async_route[/bp/] - assert b'GET' in b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Int...
FAILED tests/test_async.py::test_async_error_handler[/error] - assert 500 == 412
FAILED tests/test_async.py::test_async_error_handler[/bp/error] - assert 500 == 412
FAILED tests/test_async.py::test_async_before_after_request - assert False
```

In all cases, the underlying reason seems to be a `DeprecationWarning` triggered inside asgiref, e.g.:

```pytb
______________________________________________________________ test_async_route[/] _______________________________________________________________
tests/test_async.py:64: in test_async_route
    assert b"GET" in response.get_data()
E   assert b'GET' in b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Serv...nd was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
E    +  where b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Serv...nd was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n' = <bound method Response.get_data of <WrapperTestResponse 290 bytes [500 INTERNAL SERVER ERROR]>>()
E    +    where <bound method Response.get_data of <WrapperTestResponse 290 bytes [500 INTERNAL SERVER ERROR]>> = <WrapperTestResponse 290 bytes [500 INTERNAL SERVER ERROR]>.get_data
--------------------------------------------------------------- Captured log call ----------------------------------------------------------------
ERROR    test_async:app.py:1441 Exception on / [GET]
Traceback (most recent call last):
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/flask/app.py", line 2052, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/flask/app.py", line 1502, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/flask/app.py", line 1500, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/flask/app.py", line 1486, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/flask/app.py", line 1583, in ensure_sync
    return self.async_to_sync(func)
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/flask/app.py", line 1615, in async_to_sync
    return asgiref_async_to_sync(func)
  File "/tmp/flask/.tox/py310/lib/python3.10/site-packages/asgiref/sync.py", line 135, in __init__
    self.main_event_loop = asyncio.get_event_loop()
DeprecationWarning: There is no current event loop

```

I don't really know whether the problem is in asgiref itself, or in the way Flask is calling it. If you believe it's the former, I can file a bug for asgiref instead.

The problem can reliably be reproduced by running `tox -e py310`.

BTW if you consider testing on 3.10-dev valuable, I can submit a PR to add it to GHA workflows.

Environment:

- Python version: 3.10.0b1
- Flask version: 9039534eee6a87da98a1dee9e4338d1b73e861f8

**Comment by pgjones** [comment]
I think this is an asgiref bug - I think 3.10 has changed `asyncio.get_event_loop()` such that it no longer creates a loop if one isn't available.

**Comment by mgorny** [comment]
> I think this is an asgiref bug - I think 3.10 has changed `asyncio.get_event_loop()` such that it no longer creates a loop if one isn't available.

That's true. What I was wondering is whether it's correct to call `asgiref_async_to_sync()` without an event loop.

**Comment by mgorny** [comment]
Ok, I've figured out that I needed to enable warnings in asgiref's pytest, and then I can reproduce it with their own test suite. Filed https://github.com/django/asgiref/issues/260

**Comment by davidism** [comment]
Closing as this is an asgiref issue.
