### ISSUE TITLE
ValueError: usegmt option requires a UTC datetime

### ISSUE THREAD

**Issue by clemefr** [pallets/flask#4212]
After ugrading flask 1.1.1 to 2.0.1, I got the following error

```
[2021-08-01 17:01:05,522] ERROR in app: Exception on /data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1537, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1886, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/lib/python3.7/dist-packages/flask/sessions.py", line 394, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/itsdangerous/serializer.py", line 207, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/usr/local/lib/python3.7/dist-packages/itsdangerous/url_safe.py", line 53, in dump_payload
    json = super().dump_payload(obj)
  File "/usr/local/lib/python3.7/dist-packages/itsdangerous/serializer.py", line 169, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 308, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 290, in tag
    return tag.tag(value)
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 125, in to_json
    return {k: self.serializer.tag(v) for k, v in value.items()}
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 125, in <dictcomp>
    return {k: self.serializer.tag(v) for k, v in value.items()}
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 290, in tag
    return tag.tag(value)
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 87, in tag
    return {self.key: self.to_json(value)}
  File "/usr/local/lib/python3.7/dist-packages/flask/json/tag.py", line 210, in to_json
    return http_date(value)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/http.py", line 992, in http_date
    return email.utils.format_datetime(timestamp, usegmt=True)
  File "/usr/lib/python3.7/email/utils.py", line 165, in format_datetime
    raise ValueError("usegmt option requires a UTC datetime")
ValueError: usegmt option requires a UTC datetime
```

didn't change anything of my previous working code...

Environment:

- Python version: 3.7
- Flask version: 2.0.1

**Comment by clemefr** [comment]
Oohhh....just find that I save in session pendulum date....Now I save datetime.now() date and the problem is solved !!!!
