### ISSUE TITLE
HEAD request throws exception while doc says it should automatically be handled

### ISSUE THREAD

**Issue by solsticedhiver** [pallets/flask#4236]
When running flask app with a route like:

```
@current_app.route('/contact.html', methods=['GET', 'POST'])
def contact():
    if request.method == 'GET':
        # some code
    if request.method == 'POST':
        # some code
```

Requesting a `HEAD` on that route throws an expection like:

```
"HEAD /contact.html HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'contact' did not return a valid response. The function either returned None or ended without a return statement.
```

But the doc says that:

> If GET is present, Flask automatically adds support for the HEAD method and handles HEAD requests according to the HTTP RFC. Likewise, OPTIONS is automatically implemented for you.

https://flask.palletsprojects.com/en/2.0.x/quickstart/#http-methods

What is happening is that no code is run on that route on a `HEAD` request.

One fix is to add an `or` to the `if request.method == GET` to deal with the `HEAD` request.

But may be the doc is wrong ? Or could be more clear ?

**Comment by jugmac00** [comment]
Link to documentation would be helpful.

**Comment by solsticedhiver** [comment]
Link added above

**Comment by Yourun-proger** [comment]
@solsticedhiver, i think this Exception was raise be cause in your code don't exist condition for catching `HEAD` method.
UPDATE:
```py
from flask import Flask, request
app = Flask(__name__)
@app.route('/some', methods=['GET', 'POST'])
def some():
    if request.method == 'GET':
        return 'this is GET'
    elif request.method == 'POST':
        return 'this is POST'
    elif request.method == 'HEAD':
        return "this is HEAD"
# in the comments below I add the output for each method
print(app.test_client().head('/some').data.decode('utf-8')) # Nothing (empty string)
print(app.test_client().get('/some').data.decode('utf-8')) # this is GET
print(app.test_client().post('/some').data.decode('utf-8')) # this is POST
```
This is really strange...

**Comment by davidism** [comment]
The view still needs to return a response. All HEAD does is return what GET would without the body. This is why you normally don't see the code for GET inside an if block.
