### ISSUE TITLE
Docs - fileuploads slight mistake

### ISSUE THREAD

**Issue by jamesefhawkins** [pallets/flask#4393]
First time contributor / noob - bear with me:

Here's a screen shot from the [docs relating to fileuploads](https://flask.palletsprojects.com/en/2.0.x/patterns/fileuploads/).
<img width="867" alt="Screenshot 2021-12-28 at 16 06 20" src="https://user-images.githubusercontent.com/47497682/147584839-ed2319c7-5d49-4059-8bac-372f474a51ad.png">

`return redirect(url_for('download_file', name=filename))` gives this error:

```
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Dec/2021 15:59:48] "GET / HTTP/1.1" 200 -
[2021-12-28 15:59:53,934] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jameshawkins/Documents/internallinker/app.py", line 35, in upload_file
    return redirect(url_for('download_file', name=filename))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'download_file' with values ['name']. Did you mean 'upload_file' instead?
```
As per the error code, I presume `return redirect(url_for('download_file', name=filename))` should be replaced with `return redirect(url_for('upload_file', name=filename))`

Environment:

- just reading the docs

**Comment by ThiefMaster** [comment]
It's added later in the guide:

```python
@app.route('/uploads/<name>')
def download_file(name):
    return send_from_directory(app.config["UPLOAD_FOLDER"], name)
```
