### ISSUE TITLE
SyntaxError: invalid syntax <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"

### ISSUE THREAD

**Issue by colynhn** [pallets/flask#4396]
Environment:

- Python version: 3.8
- Flask version: 1.1.2

Details:
Server :

```
Traceback (most recent call last):
  File ".../python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File ".../python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File ".../python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File ".../python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File ".../python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File ".../python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".../python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File ".../python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
Client: 
    s = eval(requests.get(url_template.format(query)).text)["property"]
  File "<string>", line 1
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    ^
SyntaxError: invalid syntax
```

how can i fix it? thank you.

**Comment by ThiefMaster** [comment]
Why would you EVER call `eval()` on code downloaded from a remote URL? Anyway, this is clearly not a flask error since you try to execute code downloaded from somewhere else, but get HTML instead.

PS: DO NOT `eval()` (or exec) code from a remote URL,.

**Comment by colynhn** [comment]
i am fresh on this, thanks.
