### ISSUE TITLE
TypeError: redirect() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by stanphish** [pallets/flask#4410]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/binance/main.py", line 51, in index
    return redirect("/register")
TypeError: redirect() takes 0 positional arguments but 1 was given
[2022-01-10 06:19:43,514] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/binance/main.py", line 51, in index
    return redirect("/register")
TypeError: redirect() takes 0 positional arguments but 1 was given

Environment:nginx

- Python version:3.8.10
- Flask version:last version

**Comment by davidism** [comment]
I can't reproduce this issue with the information given.

**Comment by ThiefMaster** [comment]
you're probably importing redirect from elsewhere or redefine it locally

**Comment by stanphish** [comment]
> you're probably importing redirect from elsewhere or redefine it locally

from flask import render_template, Flask, session, redirect, request, g, url_for
