### ISSUE TITLE
Problems with blueprint registration

### ISSUE THREAD

**Issue by ponodoro** [pallets/flask#4421]
Hi, i creating the modular system for my project on Flask. And i got problems with blueprint registration.

Example of my code:
```
for url_prefix, blueprint in blueprints.items():
    self.Gateway.register_blueprint(blueprint=blueprint, url_prefix=url_prefix)
```

Exception from Flask:
```
Traceback (most recent call last):
  File "D:\repos\UniServices\main.py", line 13, in <module>
  File "D:\repos\UniServices\main.py", line 10, in main
    Server(configuration_file='../configuration.json').run()
  File "D:\repos\UniServices\Server\Server.py", line 30, in __init__
    self.setup(configuration_file)
  File "D:\repos\UniServices\Server\Server.py", line 45, in setup
    self.Gateway.register_blueprint(blueprint=blueprint, url_prefix=url_prefix)
  File "D:\repos\UniServices\venv\lib\site-packages\flask\scaffold.py", line 57, in wrapper_func
  File "D:\repos\UniServices\venv\lib\site-packages\flask\app.py", line 1028, in register_blueprint
    blueprint.register(self, options)
TypeError: Blueprint.register() missing 1 required positional argument: 'options'
```

I have dictionary with blueprints for automatically adding blueprints.

Code from Blueprints module
```
from .Blueprints.IndexBlueprint import Blueprint as IndexBlueprint


blueprints = {
    '/': IndexBlueprint,
}
```

Environment:

- Python version: 3.10.1
- Flask version: 2.0.2

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided.

Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.
