### ISSUE TITLE
app.view_functions occurs endpoint key missing when adding url  rule by endpoint(decorator method) of blueprint

### ISSUE THREAD

**Issue by sunsongpy** [pallets/flask#4472]
**here is a simple example:**
```py
from flask import Flask, Blueprint

app = Flask(__name__, static_folder=None)


api_v1_bp = Blueprint('api_v1', __name__, url_prefix='/api/v1')

api_v1_bp.add_url_rule('/foo', 'foo')


@api_v1_bp.endpoint('foo')
def foo():
    return 'foo'


app.register_blueprint(api_v1_bp)

app.run()
```

```
[2022-03-01 18:29:29,362] ERROR in app: Exception on /api/v1/foo [GET]
Traceback (most recent call last):
  File "E:\languages\python\3.8\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\languages\python\3.8\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\languages\python\3.8\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\languages\python\3.8\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
KeyError: 'api_v1.foo'
127.0.0.1 - - [01/Mar/2022 18:29:29] "GET /api/v1/foo HTTP/1.1" 500 -
```

rasie keyError when visit /api/v1/foo；although app.url_map._rules contains a rule of **<Rule '/api/v1/foo' (HEAD, OPTIONS, GET) -> api_v1.foo>,** app.view_function only has the "foo" key, not "api_v1.foo"

**i think problem is here**
https://github.com/pallets/flask/blob/6f7762538bffe3ce9d03508ecab230bfff3e3dcd/src/flask/blueprints.py#L357

 the line code should be **app.view_functions[f'{name}.{endpoint}'] = func**, when merging blueprint's view_functions into parent, should take blueprint name or combination of nest blueprints's name

Environment:

- Python version: 3.8
- Flask version: 2.0.2

**Comment by sunsongpy** [comment]
`
@api_v1_bp.endpoint('api_v1.foo')
def foo():
    return 'foo'
`
this is will be ok. but i think the job should be done in blueprint's register method, like this
`
def register(self, app: "Flask", options: dict) -> None:
            ....
            for endpoint, func in self.view_functions.items():
                endpoint = name + '.' + endpoint.split('.')[-1]
                app.view_functions[endpoint] = func
            ...
`
