### ISSUE TITLE
jsonify() can't serialize <class 'werkzeug.local.LocalProxy'> during debug mode

### ISSUE THREAD

**Issue by xzava** [pallets/flask#4609]
During `app.debug = True`

jsonify can serialize a LocalProxy()

Then `app.debug = False`

This error shows.

```bash
[2022-05-26 13:57:45,664] ERROR in app: Exception on /api/optional-scoped [GET]
Traceback (most recent call last):
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/mike/work/Unfinished/microauth/client/app/src/client.py", line 591, in wrapped_function
    return f(*args, **kwargs)
  File "/home/mike/work/Unfinished/microauth/client/app/src/main.py", line 221, in optional_scoped
    return jsonify(message="Hello from an optional endpoint!", current_error=current_error)
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/mike/work/Unfinished/microauth/client/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict is not JSON serializable

```

The var current_error is added to the stack in a wrapper, its the same each time

`_request_ctx_stack.top.current_error = {'code': 'invalid_request', 'description': 'Authorization header is expected'}`

```python
#> type(current_error):  <class 'werkzeug.local.LocalProxy'>
#> current_error:  {'code': 'invalid_request', 'description': 'Authorization header is expected'}
```

```python

# Works on debug, breaks when debug is turned off.
return jsonify(message="Hello from an optional endpoint!", current_error=current_error)

# Converting `LocalProxy` to dict solves the problem, but current_error could be None, which would break. 
return jsonify(message="Hello from an optional endpoint!", current_error=dict(current_error))

```

Expected behavior - jsonify to act the same torwards data regardless of debug mode. The problem is likely in how flasks json encoder works, but I could not find the error location.

Environment:

- Python version: Python 3.9.7 (default, Sep 10 2021, 00:03:59)  [GCC 7.5.0] on linux
- Flask version: Flask==2.1.2

**Comment by davidism** [comment]
LocalProxy is not intended to be serialized. Dereference it to the actual object it points to first. No clue why it works in some cases, but it does weird stuff in general with the Python object model, that probably messes with Python's json implementation.
