### ISSUE TITLE
flask.json.dumps fails for dicitonaries with mixed string + integer keys

### ISSUE THREAD

**Issue by solsword** [pallets/flask#4653]
The flask JSON module likely tries to sort keys before skipping or converting non-string keys to strings, resulting in a `TypeError` about comparisons when a dictionary with mixed string and non-string keys is provided, instead of correctly converting the non-string keys to strings.

Snippets to reproduce:

Python's built-in json behavior:

```
obj = {'hi': 'bye', 1: 2}
import json
print(json.dumps(obj))
```

prints:

`{"hi": "bye", "1": 2}`

Now with `flask.json`:

```
obj = {'hi': 'bye', 1: 2}
from flask import json
print(json.dumps(obj))
```

We get a `TypeError`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'int' and 'str'
```

It works correctly if `sort_keys=False` is provided.

The fix is almost certainly to to string coercion of keys before key sorting is attempted, although I'm not sure how complicated it is to do that.

Environment:

- Python version: 3.10.2
- Flask version: 2.1.2

**Comment by solsword** [comment]
I'm well aware that JSON only allows string keys, but [the documentation for `flask.json.dumps`](https://flask.palletsprojects.com/en/2.1.x/api/#flask.json.dumps) simply refers to [the documentation for built-in `json.dumps`](https://docs.python.org/3/library/json.html#json.dumps) which explicitly mentions the built-in behavior that non-string keys are **automatically converted to strings**.

At minimum if this behavior difference between built-in `json.dumps` and flask's version isn't seen as a bug, the documentation should be updated to indicate the difference, along the lines of: "`flask.json.dumps` automatically converts non-string keys to strings, unless string and non-string keys are mixed, in which case it throws a `TypeError`."
