### ISSUE TITLE
make_response(…) won't accept a MappingProxyType object as a view's return-value

### ISSUE THREAD

**Issue by JamesCropcho** [pallets/flask#5172]
# `make_response(…)` Won't Accept a `MappingProxyType` Object As a View's Return-Value

# Replicative Demonstration

## app.py

```python
from types import MappingProxyType

from flask import Flask

app = Flask(__name__)

response_body_dict         = dict(            { 'spam': 'eggs' })
response_body_mappingproxy = MappingProxyType({ 'spam': 'eggs' })

assert response_body_dict == response_body_mappingproxy

@app.route("/with-dict")
def with_dict():
    return response_body_dict

@app.route("/with-mappingproxytype")
def with_mappingproxytype():
    return response_body_mappingproxy
```

## Shell (*Tab A*)

```bash
flask --debug run
```

## Shell (*Tab B*)

```bash
$ curl localhost:5000/with-dict
{
  "spam": "eggs"
}
```

```bash
$ curl localhost:5000/with-mappingproxytype

Traceback (most recent call last):
  File "/home/j/.local/share/virtualenvs/flask-mappingproxy-814v2y5D/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/.local/share/virtualenvs/flask-mappingproxy-814v2y5D/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/.local/share/virtualenvs/flask-mappingproxy-814v2y5D/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/.local/share/virtualenvs/flask-mappingproxy-814v2y5D/lib/python3.11/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/.local/share/virtualenvs/flask-mappingproxy-814v2y5D/lib/python3.11/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/.local/share/virtualenvs/flask-mappingproxy-814v2y5D/lib/python3.11/site-packages/flask/app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a mappingproxy.
```
*(above response is abridged)*

# Environment

- Python version: CPython 3.11.4
- Flask version: 2.3.2

# Cf.

> **See also:** `types.MappingProxyType` can be used to create a read-only view of a `dict`.

[https://docs.python.org/3/library/stdtypes.html#mapping-types-dict](https://docs.python.org/3/library/stdtypes.html#mapping-types-dict)

>  **class `types.MappingProxyType(mapping)`**
>
>    Read-only proxy of a mapping. It provides a dynamic view on the mapping’s entries, which means that when the mapping changes, the view reflects these changes.

[https://docs.python.org/3/library/types.html#types.MappingProxyType](https://docs.python.org/3/library/types.html#types.MappingProxyType)

**Comment by davidism** [comment]
That's right, it specifically accepts a dict. I don't plan to change this. You can override Flask.make_reaponse to handle whatever you need.
