### ISSUE TITLE
Import error in Flask version 3.0.0

### ISSUE THREAD

**Issue by sneha-lodha** [pallets/flask#5282]
After updating the flask version, I wanted to run my server as usual, but encountered the following message:

Traceback (most recent call last):
  File "/Users/ft61dv/Desktop/Enablers/P05182-Asgard/server.py", line 2, in <module>
    from flask_mysqldb import MySQL
  File "/Users/ft61dv/Library/Python/3.12/lib/python/site-packages/flask_mysqldb/__init__.py", line 3, in <module>
    from flask import _app_ctx_stack, current_app
ImportError: cannot import name '_app_ctx_stack' from 'flask' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/__init__.py)

The application was working fine before this update. To get it to work again, I downgraded my flask version back to 2.3.3

Environment:

- Python version: 3.12.0
- Flask version: 3.0.0

**Comment by ThiefMaster** [comment]
You need to read changelogs before updating and should check deprecation warnings. You also need to pin your dependencies to avoid getting surprise updates from new major releases.

Also, this is an issue with flask-mysqldb which needs to be updated to support recent Flask versions.
