### ISSUE TITLE
Cannot import Markup from flask (v3.0.0) 

### ISSUE THREAD

**Issue by unsliced** [pallets/flask#5353]
As [previously reported](https://github.com/pallets/flask/issues/5084). 

### A

```python
import flask

print(flask.Markup('hi'))
```

 

```text
Traceback (most recent call last):
  File "/tmp/fl/mu1.py", line 3, in <module>
    print(flask.Markup('hi'))
  File "/tmp/fl/.venv/lib/python3.10/site-packages/flask/__init__.py", line 60, in __getattr__
    raise AttributeError(name)
AttributeError: Markup
```

### B
```python
from flask import Markup

print(Markup('hi'))
```
 
```
Traceback (most recent call last):
  File "/tmp/fl/mu2.py", line 1, in <module>
    from flask import Markup
ImportError: cannot import name 'Markup' from 'flask' (/tmp/fl/.venv/lib/python3.10/site-packages/flask/__init__.py)
```

Environment:

- Python version: 3.10.12
- Flask version: 3.0.0
- (and flask-misaka-1.0.0 but I don't think that's relevant)

**Comment by ThiefMaster** [comment]
import it from `markupsafe` instead of from `flask`.
